//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Wed Nov 10 22:15:15 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// getMemAddr_mv                  O    23 reg
// RDY_getMemAddr_mv              O     1
// maxStore                       O    38 reg
// RDY_maxStore                   O     1 reg
// RDY_putMemVal_ma               O     1
// RDY_putInpVal_ma               O     1 reg
// traceStore_mav                 O    20 reg
// RDY_traceStore_mav             O     1
// traceWrite_mav                 O    20
// RDY_traceWrite_mav             O     1
// getBackTrack_mv                O    15
// RDY_getBackTrack_mv            O     1
// RDY_putBackTrack_ma            O     1 const
// outputPrint_mav                O    32
// RDY_outputPrint_mav            O     1
// RDY_putInitial_ma              O     1
// outputPrint0_mav               O    32 const
// RDY_outputPrint0_mav           O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// putMemVal_ma_d                 I    32
// putMemVal_ma_d1                I    32
// putInpVal_ma_in                I    32 reg
// putBackTrack_ma_storedVal      I     5
// putInitial_ma_n                I    32 reg
// putInitial_ma_m                I    32 reg
// EN_putMemVal_ma                I     1
// EN_putInpVal_ma                I     1
// EN_putBackTrack_ma             I     1
// EN_putInitial_ma               I     1
// EN_maxStore                    I     1
// EN_traceStore_mav              I     1
// EN_traceWrite_mav              I     1
// EN_getBackTrack_mv             I     1
// EN_outputPrint_mav             I     1
// EN_outputPrint0_mav            I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkdut(CLK,
	     RST_N,

	     getMemAddr_mv,
	     RDY_getMemAddr_mv,

	     EN_maxStore,
	     maxStore,
	     RDY_maxStore,

	     putMemVal_ma_d,
	     putMemVal_ma_d1,
	     EN_putMemVal_ma,
	     RDY_putMemVal_ma,

	     putInpVal_ma_in,
	     EN_putInpVal_ma,
	     RDY_putInpVal_ma,

	     EN_traceStore_mav,
	     traceStore_mav,
	     RDY_traceStore_mav,

	     EN_traceWrite_mav,
	     traceWrite_mav,
	     RDY_traceWrite_mav,

	     EN_getBackTrack_mv,
	     getBackTrack_mv,
	     RDY_getBackTrack_mv,

	     putBackTrack_ma_storedVal,
	     EN_putBackTrack_ma,
	     RDY_putBackTrack_ma,

	     EN_outputPrint_mav,
	     outputPrint_mav,
	     RDY_outputPrint_mav,

	     putInitial_ma_n,
	     putInitial_ma_m,
	     EN_putInitial_ma,
	     RDY_putInitial_ma,

	     EN_outputPrint0_mav,
	     outputPrint0_mav,
	     RDY_outputPrint0_mav);
  input  CLK;
  input  RST_N;

  // value method getMemAddr_mv
  output [22 : 0] getMemAddr_mv;
  output RDY_getMemAddr_mv;

  // actionvalue method maxStore
  input  EN_maxStore;
  output [37 : 0] maxStore;
  output RDY_maxStore;

  // action method putMemVal_ma
  input  [31 : 0] putMemVal_ma_d;
  input  [31 : 0] putMemVal_ma_d1;
  input  EN_putMemVal_ma;
  output RDY_putMemVal_ma;

  // action method putInpVal_ma
  input  [31 : 0] putInpVal_ma_in;
  input  EN_putInpVal_ma;
  output RDY_putInpVal_ma;

  // actionvalue method traceStore_mav
  input  EN_traceStore_mav;
  output [19 : 0] traceStore_mav;
  output RDY_traceStore_mav;

  // actionvalue method traceWrite_mav
  input  EN_traceWrite_mav;
  output [19 : 0] traceWrite_mav;
  output RDY_traceWrite_mav;

  // actionvalue method getBackTrack_mv
  input  EN_getBackTrack_mv;
  output [14 : 0] getBackTrack_mv;
  output RDY_getBackTrack_mv;

  // action method putBackTrack_ma
  input  [4 : 0] putBackTrack_ma_storedVal;
  input  EN_putBackTrack_ma;
  output RDY_putBackTrack_ma;

  // actionvalue method outputPrint_mav
  input  EN_outputPrint_mav;
  output [31 : 0] outputPrint_mav;
  output RDY_outputPrint_mav;

  // action method putInitial_ma
  input  [31 : 0] putInitial_ma_n;
  input  [31 : 0] putInitial_ma_m;
  input  EN_putInitial_ma;
  output RDY_putInitial_ma;

  // actionvalue method outputPrint0_mav
  input  EN_outputPrint0_mav;
  output [31 : 0] outputPrint0_mav;
  output RDY_outputPrint0_mav;

  // signals for module outputs
  wire [37 : 0] maxStore;
  wire [31 : 0] outputPrint0_mav, outputPrint_mav;
  wire [22 : 0] getMemAddr_mv;
  wire [19 : 0] traceStore_mav, traceWrite_mav;
  wire [14 : 0] getBackTrack_mv;
  wire RDY_getBackTrack_mv,
       RDY_getMemAddr_mv,
       RDY_maxStore,
       RDY_outputPrint0_mav,
       RDY_outputPrint_mav,
       RDY_putBackTrack_ma,
       RDY_putInitial_ma,
       RDY_putInpVal_ma,
       RDY_putMemVal_ma,
       RDY_traceStore_mav,
       RDY_traceWrite_mav;

  // inlined wires
  wire clear_inter_stall_dly_1_wget,
       clear_inter_stall_dly_1_whas,
       clear_stall_dly_1_wget,
       clear_stall_dly_1_whas,
       fPrint_dreg_1_whas;

  // register backTrackReg_0
  reg [4 : 0] backTrackReg_0;
  wire [4 : 0] backTrackReg_0_D_IN;
  wire backTrackReg_0_EN;

  // register backTrackReg_1
  reg [4 : 0] backTrackReg_1;
  wire [4 : 0] backTrackReg_1_D_IN;
  wire backTrackReg_1_EN;

  // register clear_inter_stall_dly
  reg clear_inter_stall_dly;
  wire clear_inter_stall_dly_D_IN, clear_inter_stall_dly_EN;

  // register clear_stall_dly
  reg clear_stall_dly;
  wire clear_stall_dly_D_IN, clear_stall_dly_EN;

  // register countTime
  reg [9 : 0] countTime;
  reg [9 : 0] countTime_D_IN;
  wire countTime_EN;

  // register done
  reg done;
  wire done_D_IN, done_EN;

  // register emiss_stage1
  reg emiss_stage1;
  reg emiss_stage1_D_IN;
  wire emiss_stage1_EN;

  // register fPrint_dreg
  reg fPrint_dreg;
  wire fPrint_dreg_D_IN, fPrint_dreg_EN;

  // register iCounter_Comp
  reg [4 : 0] iCounter_Comp;
  reg [4 : 0] iCounter_Comp_D_IN;
  wire iCounter_Comp_EN;

  // register iCounter_stage1
  reg [4 : 0] iCounter_stage1;
  reg [4 : 0] iCounter_stage1_D_IN;
  wire iCounter_stage1_EN;

  // register index
  reg index;
  reg index_D_IN;
  wire index_EN;

  // register inpIsFirst_stage1
  reg inpIsFirst_stage1;
  wire inpIsFirst_stage1_D_IN, inpIsFirst_stage1_EN;

  // register jCounter_Comp
  reg [4 : 0] jCounter_Comp;
  reg [4 : 0] jCounter_Comp_D_IN;
  wire jCounter_Comp_EN;

  // register jCounter_stage1
  reg [4 : 0] jCounter_stage1;
  wire [4 : 0] jCounter_stage1_D_IN;
  wire jCounter_stage1_EN;

  // register numObs
  reg [8 : 0] numObs;
  wire [8 : 0] numObs_D_IN;
  wire numObs_EN;

  // register numStates
  reg [4 : 0] numStates;
  wire [4 : 0] numStates_D_IN;
  wire numStates_EN;

  // register tempMaxi
  reg [36 : 0] tempMaxi;
  reg [36 : 0] tempMaxi_D_IN;
  wire tempMaxi_EN;

  // register tempMaxj
  reg [36 : 0] tempMaxj;
  reg [36 : 0] tempMaxj_D_IN;
  wire tempMaxj_EN;

  // register timeS
  reg [9 : 0] timeS;
  reg [9 : 0] timeS_D_IN;
  wire timeS_EN;

  // register timeTotal
  reg [9 : 0] timeTotal;
  wire [9 : 0] timeTotal_D_IN;
  wire timeTotal_EN;

  // register traceStage_State
  reg [1 : 0] traceStage_State;
  reg [1 : 0] traceStage_State_D_IN;
  wire traceStage_State_EN;

  // register valOut
  reg [31 : 0] valOut;
  wire [31 : 0] valOut_D_IN;
  wire valOut_EN;

  // register valPrint_dreg
  reg valPrint_dreg;
  wire valPrint_dreg_D_IN, valPrint_dreg_EN;

  // register viterbiState
  reg [1 : 0] viterbiState;
  wire [1 : 0] viterbiState_D_IN;
  wire viterbiState_EN;

  // register vt_inter_is_ready
  reg vt_inter_is_ready;
  wire vt_inter_is_ready_D_IN, vt_inter_is_ready_EN;

  // register vt_is_ready
  reg vt_is_ready;
  wire vt_is_ready_D_IN, vt_is_ready_EN;

  // ports of submodule fpadder
  wire [31 : 0] fpadder_get, fpadder_put_a, fpadder_put_b;
  wire fpadder_EN_get, fpadder_EN_put, fpadder_RDY_get, fpadder_RDY_put;

  // ports of submodule inp_F
  wire [8 : 0] inp_F_D_IN, inp_F_D_OUT;
  wire inp_F_CLR, inp_F_DEQ, inp_F_EMPTY_N, inp_F_ENQ, inp_F_FULL_N;

  // ports of submodule metadata_fifo
  wire [3 : 0] metadata_fifo_D_IN, metadata_fifo_D_OUT;
  wire metadata_fifo_CLR,
       metadata_fifo_DEQ,
       metadata_fifo_EMPTY_N,
       metadata_fifo_ENQ,
       metadata_fifo_FULL_N;

  // ports of submodule preAdd_F
  wire [67 : 0] preAdd_F_D_IN, preAdd_F_D_OUT;
  wire preAdd_F_CLR,
       preAdd_F_DEQ,
       preAdd_F_EMPTY_N,
       preAdd_F_ENQ,
       preAdd_F_FULL_N;

  // ports of submodule preCom_F
  wire [35 : 0] preCom_F_D_IN, preCom_F_D_OUT;
  wire preCom_F_CLR,
       preCom_F_DEQ,
       preCom_F_EMPTY_N,
       preCom_F_ENQ,
       preCom_F_FULL_N;

  // ports of submodule preMax_F
  reg [37 : 0] preMax_F_D_IN;
  wire [37 : 0] preMax_F_D_OUT;
  wire preMax_F_CLR,
       preMax_F_DEQ,
       preMax_F_EMPTY_N,
       preMax_F_ENQ,
       preMax_F_FULL_N;

  // ports of submodule preMem_F
  reg [22 : 0] preMem_F_D_IN;
  wire [22 : 0] preMem_F_D_OUT;
  wire preMem_F_CLR,
       preMem_F_DEQ,
       preMem_F_EMPTY_N,
       preMem_F_ENQ,
       preMem_F_FULL_N;

  // ports of submodule preTrace_F
  reg [21 : 0] preTrace_F_D_IN;
  wire [21 : 0] preTrace_F_D_OUT;
  wire preTrace_F_CLR,
       preTrace_F_DEQ,
       preTrace_F_EMPTY_N,
       preTrace_F_ENQ,
       preTrace_F_FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_clear_inter_stall_dly__dreg_update,
       CAN_FIRE_RL_clear_stall_dly__dreg_update,
       CAN_FIRE_RL_compare_Stage_Emission,
       CAN_FIRE_RL_compare_Stage_EndMarker,
       CAN_FIRE_RL_compare_Stage_First,
       CAN_FIRE_RL_compare_Stage_Transition,
       CAN_FIRE_RL_compare_stage_zero,
       CAN_FIRE_RL_fPrint_dreg__dreg_update,
       CAN_FIRE_RL_feed_adder_stage1,
       CAN_FIRE_RL_memEnd_handle,
       CAN_FIRE_RL_retrieve_from_adder_stage2,
       CAN_FIRE_RL_rl_clear_inter_stall_delay,
       CAN_FIRE_RL_rl_clear_stall_delay,
       CAN_FIRE_RL_stage_1_Endmark,
       CAN_FIRE_RL_stage_1_FirstInp,
       CAN_FIRE_RL_stage_1_Normal_Emiss,
       CAN_FIRE_RL_stage_1_Normal_Trans,
       CAN_FIRE_RL_stage_1_zero,
       CAN_FIRE_RL_trace_stage_endstore,
       CAN_FIRE_RL_valPrint_dreg__dreg_update,
       CAN_FIRE_RL_wireend,
       CAN_FIRE_RL_wirezero,
       CAN_FIRE_getBackTrack_mv,
       CAN_FIRE_maxStore,
       CAN_FIRE_outputPrint0_mav,
       CAN_FIRE_outputPrint_mav,
       CAN_FIRE_putBackTrack_ma,
       CAN_FIRE_putInitial_ma,
       CAN_FIRE_putInpVal_ma,
       CAN_FIRE_putMemVal_ma,
       CAN_FIRE_traceStore_mav,
       CAN_FIRE_traceWrite_mav,
       WILL_FIRE_RL_clear_inter_stall_dly__dreg_update,
       WILL_FIRE_RL_clear_stall_dly__dreg_update,
       WILL_FIRE_RL_compare_Stage_Emission,
       WILL_FIRE_RL_compare_Stage_EndMarker,
       WILL_FIRE_RL_compare_Stage_First,
       WILL_FIRE_RL_compare_Stage_Transition,
       WILL_FIRE_RL_compare_stage_zero,
       WILL_FIRE_RL_fPrint_dreg__dreg_update,
       WILL_FIRE_RL_feed_adder_stage1,
       WILL_FIRE_RL_memEnd_handle,
       WILL_FIRE_RL_retrieve_from_adder_stage2,
       WILL_FIRE_RL_rl_clear_inter_stall_delay,
       WILL_FIRE_RL_rl_clear_stall_delay,
       WILL_FIRE_RL_stage_1_Endmark,
       WILL_FIRE_RL_stage_1_FirstInp,
       WILL_FIRE_RL_stage_1_Normal_Emiss,
       WILL_FIRE_RL_stage_1_Normal_Trans,
       WILL_FIRE_RL_stage_1_zero,
       WILL_FIRE_RL_trace_stage_endstore,
       WILL_FIRE_RL_valPrint_dreg__dreg_update,
       WILL_FIRE_RL_wireend,
       WILL_FIRE_RL_wirezero,
       WILL_FIRE_getBackTrack_mv,
       WILL_FIRE_maxStore,
       WILL_FIRE_outputPrint0_mav,
       WILL_FIRE_outputPrint_mav,
       WILL_FIRE_putBackTrack_ma,
       WILL_FIRE_putInitial_ma,
       WILL_FIRE_putInpVal_ma,
       WILL_FIRE_putMemVal_ma,
       WILL_FIRE_traceStore_mav,
       WILL_FIRE_traceWrite_mav;

  // inputs to muxes for submodule ports
  wire [67 : 0] MUX_preAdd_F_enq_1__VAL_1, MUX_preAdd_F_enq_1__VAL_2;
  wire [37 : 0] MUX_preMax_F_enq_1__VAL_1,
		MUX_preMax_F_enq_1__VAL_2,
		MUX_preMax_F_enq_1__VAL_3;
  wire [36 : 0] MUX_tempMaxi_write_1__VAL_2, MUX_tempMaxj_write_1__VAL_2;
  wire [22 : 0] MUX_preMem_F_enq_1__VAL_1,
		MUX_preMem_F_enq_1__VAL_2,
		MUX_preMem_F_enq_1__VAL_3,
		MUX_preMem_F_enq_1__VAL_4;
  wire [21 : 0] MUX_preTrace_F_enq_1__VAL_1,
		MUX_preTrace_F_enq_1__VAL_2,
		MUX_preTrace_F_enq_1__VAL_3;
  wire [9 : 0] MUX_countTime_write_1__VAL_2,
	       MUX_countTime_write_1__VAL_3,
	       MUX_timeS_write_1__VAL_2;
  wire [4 : 0] MUX_iCounter_Comp_write_1__VAL_2,
	       MUX_iCounter_stage1_write_1__VAL_2,
	       MUX_jCounter_Comp_write_1__VAL_2,
	       MUX_jCounter_stage1_write_1__VAL_2;
  wire [1 : 0] MUX_traceStage_State_write_1__VAL_3;
  wire MUX_backTrackReg_0_write_1__SEL_1,
       MUX_backTrackReg_1_write_1__SEL_1,
       MUX_clear_inter_stall_dly_1_wset_1__SEL_1,
       MUX_clear_inter_stall_dly_1_wset_1__SEL_2,
       MUX_clear_stall_dly_1_wset_1__SEL_1,
       MUX_clear_stall_dly_1_wset_1__SEL_2,
       MUX_countTime_write_1__SEL_2,
       MUX_countTime_write_1__SEL_3,
       MUX_done_write_1__SEL_1,
       MUX_emiss_stage1_write_1__SEL_2,
       MUX_emiss_stage1_write_1__SEL_3,
       MUX_emiss_stage1_write_1__SEL_4,
       MUX_iCounter_Comp_write_1__SEL_3,
       MUX_iCounter_stage1_write_1__SEL_3,
       MUX_index_write_1__SEL_1,
       MUX_inpIsFirst_stage1_write_1__SEL_1,
       MUX_tempMaxi_write_1__SEL_2,
       MUX_tempMaxi_write_1__SEL_5,
       MUX_tempMaxj_write_1__SEL_2,
       MUX_traceStage_State_write_1__SEL_1,
       MUX_traceStage_State_write_1__SEL_2;

  // declarations used by system tasks
  // synopsys translate_off
  reg [63 : 0] v__h1418;
  // synopsys translate_on

  // remaining internal signals
  wire [31 : 0] v__h6852, v__h6901, x__h6067;
  wire [10 : 0] iCounter_Comp_13_CONCAT_IF_preCom_F_first__03__ETC___d155;
  wire [9 : 0] trace_enq_timestep__h3593;
  wire [8 : 0] indfi__h1651, xnt_memReq_op1_memIndex__h2060;
  wire [4 : 0] op2fi__h1652, x__h2083, x__h2275, x__h4306, x__h4583, x__h6676;
  wire NOT_traceStage_State_28_EQ_0_11_13_OR_countTim_ETC___d219,
       NOT_traceStage_State_28_EQ_0_11_13_OR_countTim_ETC___d221,
       countTime_06_EQ_timeTotal_17___d218,
       iCounter_Comp_13_EQ_numStates_4___d117,
       iCounter_stage1_3_EQ_numStates_4___d35,
       inpIsFirst_stage1_1_AND_viterbiState_0_EQ_1_1__ETC___d32,
       jCounter_Comp_41_EQ_numStates_4___d142,
       jCounter_stage1_2_EQ_numStates_4___d57,
       preCom_F_first__03_BITS_32_TO_1_14_ULT_tempMax_ETC___d122,
       preCom_F_first__03_BITS_32_TO_1_14_ULT_tempMax_ETC___d147;

  // value method getMemAddr_mv
  assign getMemAddr_mv = preMem_F_D_OUT ;
  assign RDY_getMemAddr_mv = !preMem_F_D_OUT[22] && preMem_F_EMPTY_N ;

  // actionvalue method maxStore
  assign maxStore = preMax_F_D_OUT ;
  assign RDY_maxStore = preMax_F_EMPTY_N ;
  assign CAN_FIRE_maxStore = preMax_F_EMPTY_N ;
  assign WILL_FIRE_maxStore = EN_maxStore ;

  // action method putMemVal_ma
  assign RDY_putMemVal_ma =
	     preMem_F_EMPTY_N && !preMem_F_D_OUT[22] && !preMem_F_D_OUT[0] &&
	     preAdd_F_FULL_N ;
  assign CAN_FIRE_putMemVal_ma =
	     preMem_F_EMPTY_N && !preMem_F_D_OUT[22] && !preMem_F_D_OUT[0] &&
	     preAdd_F_FULL_N ;
  assign WILL_FIRE_putMemVal_ma = EN_putMemVal_ma ;

  // action method putInpVal_ma
  assign RDY_putInpVal_ma = inp_F_FULL_N ;
  assign CAN_FIRE_putInpVal_ma = inp_F_FULL_N ;
  assign WILL_FIRE_putInpVal_ma = EN_putInpVal_ma ;

  // actionvalue method traceStore_mav
  assign traceStore_mav = preTrace_F_D_OUT[20:1] ;
  assign RDY_traceStore_mav =
	     CAN_FIRE_traceStore_mav && !WILL_FIRE_RL_trace_stage_endstore ;
  assign CAN_FIRE_traceStore_mav =
	     !CAN_FIRE_RL_wirezero && traceStage_State == 2'd1 &&
	     !CAN_FIRE_RL_wirezero &&
	     preTrace_F_EMPTY_N ;
  assign WILL_FIRE_traceStore_mav = EN_traceStore_mav ;

  // actionvalue method traceWrite_mav
  assign traceWrite_mav = { countTime, 5'd1, backTrackReg_1 } ;
  assign RDY_traceWrite_mav = traceStage_State == 2'd0 && index ;
  assign CAN_FIRE_traceWrite_mav = traceStage_State == 2'd0 && index ;
  assign WILL_FIRE_traceWrite_mav = EN_traceWrite_mav ;

  // actionvalue method getBackTrack_mv
  assign getBackTrack_mv = { countTime, x__h6676 } ;
  assign RDY_getBackTrack_mv =
	     traceStage_State == 2'd0 && countTime != 10'd0 && !index ||
	     traceStage_State == 2'd2 && !index ;
  assign CAN_FIRE_getBackTrack_mv =
	     traceStage_State == 2'd0 && countTime != 10'd0 && !index ||
	     traceStage_State == 2'd2 && !index ;
  assign WILL_FIRE_getBackTrack_mv = EN_getBackTrack_mv ;

  // action method putBackTrack_ma
  assign RDY_putBackTrack_ma = 1'd1 ;
  assign CAN_FIRE_putBackTrack_ma = 1'd1 ;
  assign WILL_FIRE_putBackTrack_ma = EN_putBackTrack_ma ;

  // actionvalue method outputPrint_mav
  assign outputPrint_mav = valPrint_dreg ? valOut : v__h6852 ;
  assign RDY_outputPrint_mav = traceStage_State == 2'd2 && index ;
  assign CAN_FIRE_outputPrint_mav = traceStage_State == 2'd2 && index ;
  assign WILL_FIRE_outputPrint_mav = EN_outputPrint_mav ;

  // action method putInitial_ma
  assign RDY_putInitial_ma = viterbiState == 2'd0 ;
  assign CAN_FIRE_putInitial_ma = viterbiState == 2'd0 ;
  assign WILL_FIRE_putInitial_ma = EN_putInitial_ma ;

  // actionvalue method outputPrint0_mav
  assign outputPrint0_mav = 32'b0 ;
  assign RDY_outputPrint0_mav =
	     CAN_FIRE_outputPrint0_mav && !WILL_FIRE_RL_trace_stage_endstore ;
  assign CAN_FIRE_outputPrint0_mav =
	     CAN_FIRE_RL_wirezero && traceStage_State == 2'd1 &&
	     preTrace_F_EMPTY_N ;
  assign WILL_FIRE_outputPrint0_mav = EN_outputPrint0_mav ;

  // submodule fpadder
  mkFPadder32 fpadder(.CLK(CLK),
		      .RST_N(RST_N),
		      .put_a(fpadder_put_a),
		      .put_b(fpadder_put_b),
		      .EN_put(fpadder_EN_put),
		      .EN_get(fpadder_EN_get),
		      .RDY_put(fpadder_RDY_put),
		      .get(fpadder_get),
		      .RDY_get(fpadder_RDY_get));

  // submodule inp_F
  FIFO2 #(.width(32'd9), .guarded(1'd1)) inp_F(.RST(RST_N),
					       .CLK(CLK),
					       .D_IN(inp_F_D_IN),
					       .ENQ(inp_F_ENQ),
					       .DEQ(inp_F_DEQ),
					       .CLR(inp_F_CLR),
					       .D_OUT(inp_F_D_OUT),
					       .FULL_N(inp_F_FULL_N),
					       .EMPTY_N(inp_F_EMPTY_N));

  // submodule metadata_fifo
  FIFO2 #(.width(32'd4), .guarded(1'd1)) metadata_fifo(.RST(RST_N),
						       .CLK(CLK),
						       .D_IN(metadata_fifo_D_IN),
						       .ENQ(metadata_fifo_ENQ),
						       .DEQ(metadata_fifo_DEQ),
						       .CLR(metadata_fifo_CLR),
						       .D_OUT(metadata_fifo_D_OUT),
						       .FULL_N(metadata_fifo_FULL_N),
						       .EMPTY_N(metadata_fifo_EMPTY_N));

  // submodule preAdd_F
  FIFO2 #(.width(32'd68), .guarded(1'd1)) preAdd_F(.RST(RST_N),
						   .CLK(CLK),
						   .D_IN(preAdd_F_D_IN),
						   .ENQ(preAdd_F_ENQ),
						   .DEQ(preAdd_F_DEQ),
						   .CLR(preAdd_F_CLR),
						   .D_OUT(preAdd_F_D_OUT),
						   .FULL_N(preAdd_F_FULL_N),
						   .EMPTY_N(preAdd_F_EMPTY_N));

  // submodule preCom_F
  FIFO2 #(.width(32'd36), .guarded(1'd1)) preCom_F(.RST(RST_N),
						   .CLK(CLK),
						   .D_IN(preCom_F_D_IN),
						   .ENQ(preCom_F_ENQ),
						   .DEQ(preCom_F_DEQ),
						   .CLR(preCom_F_CLR),
						   .D_OUT(preCom_F_D_OUT),
						   .FULL_N(preCom_F_FULL_N),
						   .EMPTY_N(preCom_F_EMPTY_N));

  // submodule preMax_F
  FIFO2 #(.width(32'd38), .guarded(1'd1)) preMax_F(.RST(RST_N),
						   .CLK(CLK),
						   .D_IN(preMax_F_D_IN),
						   .ENQ(preMax_F_ENQ),
						   .DEQ(preMax_F_DEQ),
						   .CLR(preMax_F_CLR),
						   .D_OUT(preMax_F_D_OUT),
						   .FULL_N(preMax_F_FULL_N),
						   .EMPTY_N(preMax_F_EMPTY_N));

  // submodule preMem_F
  FIFO2 #(.width(32'd23), .guarded(1'd1)) preMem_F(.RST(RST_N),
						   .CLK(CLK),
						   .D_IN(preMem_F_D_IN),
						   .ENQ(preMem_F_ENQ),
						   .DEQ(preMem_F_DEQ),
						   .CLR(preMem_F_CLR),
						   .D_OUT(preMem_F_D_OUT),
						   .FULL_N(preMem_F_FULL_N),
						   .EMPTY_N(preMem_F_EMPTY_N));

  // submodule preTrace_F
  FIFO2 #(.width(32'd22), .guarded(1'd1)) preTrace_F(.RST(RST_N),
						     .CLK(CLK),
						     .D_IN(preTrace_F_D_IN),
						     .ENQ(preTrace_F_ENQ),
						     .DEQ(preTrace_F_DEQ),
						     .CLR(preTrace_F_CLR),
						     .D_OUT(preTrace_F_D_OUT),
						     .FULL_N(preTrace_F_FULL_N),
						     .EMPTY_N(preTrace_F_EMPTY_N));

  // rule RL_stage_1_zero
  assign CAN_FIRE_RL_stage_1_zero =
	     preMem_F_FULL_N && inp_F_EMPTY_N && viterbiState == 2'd1 &&
	     inp_F_D_OUT == 9'd0 ;
  assign WILL_FIRE_RL_stage_1_zero = CAN_FIRE_RL_stage_1_zero ;

  // rule RL_stage_1_Endmark
  assign CAN_FIRE_RL_stage_1_Endmark =
	     inp_F_EMPTY_N && preMem_F_FULL_N && viterbiState == 2'd1 &&
	     inp_F_D_OUT == 9'd511 ;
  assign WILL_FIRE_RL_stage_1_Endmark = CAN_FIRE_RL_stage_1_Endmark ;

  // rule RL_stage_1_FirstInp
  assign CAN_FIRE_RL_stage_1_FirstInp =
	     preMem_F_FULL_N && inp_F_EMPTY_N &&
	     inpIsFirst_stage1_1_AND_viterbiState_0_EQ_1_1__ETC___d32 ;
  assign WILL_FIRE_RL_stage_1_FirstInp =
	     CAN_FIRE_RL_stage_1_FirstInp && !WILL_FIRE_RL_stage_1_Endmark ;

  // rule RL_stage_1_Normal_Trans
  assign CAN_FIRE_RL_stage_1_Normal_Trans =
	     preMem_F_FULL_N && !inpIsFirst_stage1 && emiss_stage1 &&
	     vt_is_ready ;
  assign WILL_FIRE_RL_stage_1_Normal_Trans =
	     CAN_FIRE_RL_stage_1_Normal_Trans &&
	     !WILL_FIRE_RL_stage_1_Endmark &&
	     !WILL_FIRE_RL_stage_1_zero ;

  // rule RL_stage_1_Normal_Emiss
  assign CAN_FIRE_RL_stage_1_Normal_Emiss =
	     inp_F_EMPTY_N && preMem_F_FULL_N && !inpIsFirst_stage1 &&
	     !emiss_stage1 &&
	     vt_inter_is_ready ;
  assign WILL_FIRE_RL_stage_1_Normal_Emiss =
	     CAN_FIRE_RL_stage_1_Normal_Emiss &&
	     !WILL_FIRE_RL_stage_1_Endmark &&
	     !WILL_FIRE_RL_stage_1_zero ;

  // rule RL_memEnd_handle
  assign CAN_FIRE_RL_memEnd_handle =
	     preMem_F_EMPTY_N && preAdd_F_FULL_N &&
	     (preMem_F_D_OUT[22] || preMem_F_D_OUT[0]) ;
  assign WILL_FIRE_RL_memEnd_handle = CAN_FIRE_RL_memEnd_handle ;

  // rule RL_feed_adder_stage1
  assign CAN_FIRE_RL_feed_adder_stage1 =
	     fpadder_RDY_put && preAdd_F_EMPTY_N && metadata_fifo_FULL_N ;
  assign WILL_FIRE_RL_feed_adder_stage1 = CAN_FIRE_RL_feed_adder_stage1 ;

  // rule RL_retrieve_from_adder_stage2
  assign CAN_FIRE_RL_retrieve_from_adder_stage2 =
	     fpadder_RDY_get && metadata_fifo_EMPTY_N && preCom_F_FULL_N ;
  assign WILL_FIRE_RL_retrieve_from_adder_stage2 =
	     CAN_FIRE_RL_retrieve_from_adder_stage2 ;

  // rule RL_rl_clear_inter_stall_delay
  assign CAN_FIRE_RL_rl_clear_inter_stall_delay = clear_inter_stall_dly ;
  assign WILL_FIRE_RL_rl_clear_inter_stall_delay = clear_inter_stall_dly ;

  // rule RL_rl_clear_stall_delay
  assign CAN_FIRE_RL_rl_clear_stall_delay = clear_stall_dly ;
  assign WILL_FIRE_RL_rl_clear_stall_delay = clear_stall_dly ;

  // rule RL_compare_stage_zero
  assign CAN_FIRE_RL_compare_stage_zero =
	     preCom_F_EMPTY_N && preTrace_F_FULL_N && preCom_F_D_OUT[0] ;
  assign WILL_FIRE_RL_compare_stage_zero = CAN_FIRE_RL_compare_stage_zero ;

  // rule RL_compare_Stage_First
  assign CAN_FIRE_RL_compare_Stage_First =
	     preCom_F_EMPTY_N && preMax_F_FULL_N && preCom_F_D_OUT[34] ;
  assign WILL_FIRE_RL_compare_Stage_First =
	     CAN_FIRE_RL_compare_Stage_First &&
	     !WILL_FIRE_RL_compare_Stage_EndMarker &&
	     !WILL_FIRE_RL_compare_stage_zero ;

  // rule RL_compare_Stage_EndMarker
  assign CAN_FIRE_RL_compare_Stage_EndMarker =
	     preCom_F_EMPTY_N && preTrace_F_FULL_N && preCom_F_D_OUT[35] &&
	     traceStage_State == 2'd1 ;
  assign WILL_FIRE_RL_compare_Stage_EndMarker =
	     CAN_FIRE_RL_compare_Stage_EndMarker &&
	     !WILL_FIRE_RL_compare_stage_zero ;

  // rule RL_compare_Stage_Transition
  assign CAN_FIRE_RL_compare_Stage_Transition =
	     preCom_F_EMPTY_N && preTrace_F_FULL_N && preMax_F_FULL_N &&
	     preCom_F_D_OUT[33] &&
	     !preCom_F_D_OUT[35] ;
  assign WILL_FIRE_RL_compare_Stage_Transition =
	     CAN_FIRE_RL_compare_Stage_Transition &&
	     !WILL_FIRE_RL_compare_Stage_First &&
	     !WILL_FIRE_RL_compare_stage_zero ;

  // rule RL_compare_Stage_Emission
  assign CAN_FIRE_RL_compare_Stage_Emission =
	     preCom_F_EMPTY_N && preMax_F_FULL_N && !preCom_F_D_OUT[33] &&
	     !preCom_F_D_OUT[35] ;
  assign WILL_FIRE_RL_compare_Stage_Emission =
	     CAN_FIRE_RL_compare_Stage_Emission &&
	     !WILL_FIRE_RL_compare_Stage_First &&
	     !WILL_FIRE_RL_compare_stage_zero ;

  // rule RL_trace_stage_endstore
  assign CAN_FIRE_RL_trace_stage_endstore =
	     preTrace_F_EMPTY_N && preTrace_F_D_OUT[21] &&
	     traceStage_State == 2'd1 &&
	     !preTrace_F_D_OUT[0] ;
  assign WILL_FIRE_RL_trace_stage_endstore =
	     CAN_FIRE_RL_trace_stage_endstore ;

  // rule RL_wirezero
  assign CAN_FIRE_RL_wirezero = preTrace_F_EMPTY_N && preTrace_F_D_OUT[0] ;
  assign WILL_FIRE_RL_wirezero = CAN_FIRE_RL_wirezero ;

  // rule RL_wireend
  assign CAN_FIRE_RL_wireend = CAN_FIRE_RL_wirezero ;
  assign WILL_FIRE_RL_wireend = CAN_FIRE_RL_wirezero ;

  // rule RL_clear_inter_stall_dly__dreg_update
  assign CAN_FIRE_RL_clear_inter_stall_dly__dreg_update = 1'd1 ;
  assign WILL_FIRE_RL_clear_inter_stall_dly__dreg_update = 1'd1 ;

  // rule RL_clear_stall_dly__dreg_update
  assign CAN_FIRE_RL_clear_stall_dly__dreg_update = 1'd1 ;
  assign WILL_FIRE_RL_clear_stall_dly__dreg_update = 1'd1 ;

  // rule RL_fPrint_dreg__dreg_update
  assign CAN_FIRE_RL_fPrint_dreg__dreg_update = 1'd1 ;
  assign WILL_FIRE_RL_fPrint_dreg__dreg_update = 1'd1 ;

  // rule RL_valPrint_dreg__dreg_update
  assign CAN_FIRE_RL_valPrint_dreg__dreg_update = 1'd1 ;
  assign WILL_FIRE_RL_valPrint_dreg__dreg_update = 1'd1 ;

  // inputs to muxes for submodule ports
  assign MUX_backTrackReg_0_write_1__SEL_1 =
	     WILL_FIRE_RL_trace_stage_endstore &&
	     preTrace_F_D_OUT[20:11] == 10'd0 ;
  assign MUX_backTrackReg_1_write_1__SEL_1 =
	     WILL_FIRE_RL_trace_stage_endstore &&
	     preTrace_F_D_OUT[20:11] != 10'd0 ;
  assign MUX_clear_inter_stall_dly_1_wset_1__SEL_1 =
	     WILL_FIRE_RL_compare_Stage_Transition &&
	     jCounter_Comp_41_EQ_numStates_4___d142 &&
	     iCounter_Comp_13_EQ_numStates_4___d117 ;
  assign MUX_clear_inter_stall_dly_1_wset_1__SEL_2 =
	     WILL_FIRE_RL_compare_Stage_First && preCom_F_D_OUT[33] &&
	     iCounter_Comp_13_EQ_numStates_4___d117 ;
  assign MUX_clear_stall_dly_1_wset_1__SEL_1 =
	     WILL_FIRE_RL_compare_Stage_Emission &&
	     iCounter_Comp_13_EQ_numStates_4___d117 ;
  assign MUX_clear_stall_dly_1_wset_1__SEL_2 =
	     WILL_FIRE_RL_compare_Stage_First && !preCom_F_D_OUT[33] &&
	     iCounter_Comp_13_EQ_numStates_4___d117 ;
  assign MUX_countTime_write_1__SEL_2 =
	     EN_traceWrite_mav && countTime != 10'd1 ;
  assign MUX_countTime_write_1__SEL_3 =
	     EN_getBackTrack_mv &&
	     NOT_traceStage_State_28_EQ_0_11_13_OR_countTim_ETC___d221 ;
  assign MUX_done_write_1__SEL_1 = EN_outputPrint_mav && done ;
  assign MUX_emiss_stage1_write_1__SEL_2 =
	     WILL_FIRE_RL_stage_1_Normal_Emiss &&
	     iCounter_stage1_3_EQ_numStates_4___d35 ;
  assign MUX_emiss_stage1_write_1__SEL_3 =
	     WILL_FIRE_RL_stage_1_Normal_Trans &&
	     jCounter_stage1_2_EQ_numStates_4___d57 &&
	     iCounter_stage1_3_EQ_numStates_4___d35 ;
  assign MUX_emiss_stage1_write_1__SEL_4 =
	     WILL_FIRE_RL_stage_1_FirstInp &&
	     iCounter_stage1_3_EQ_numStates_4___d35 ;
  assign MUX_iCounter_Comp_write_1__SEL_3 =
	     WILL_FIRE_RL_compare_Stage_Transition &&
	     jCounter_Comp_41_EQ_numStates_4___d142 ;
  assign MUX_iCounter_stage1_write_1__SEL_3 =
	     WILL_FIRE_RL_stage_1_Normal_Trans &&
	     jCounter_stage1_2_EQ_numStates_4___d57 ;
  assign MUX_index_write_1__SEL_1 =
	     EN_outputPrint_mav && !valPrint_dreg && !fPrint_dreg && !done ;
  assign MUX_inpIsFirst_stage1_write_1__SEL_1 =
	     WILL_FIRE_RL_stage_1_FirstInp &&
	     iCounter_stage1_3_EQ_numStates_4___d35 &&
	     !emiss_stage1 ;
  assign MUX_tempMaxi_write_1__SEL_2 =
	     WILL_FIRE_RL_compare_Stage_Emission &&
	     preCom_F_first__03_BITS_32_TO_1_14_ULT_tempMax_ETC___d122 ;
  assign MUX_tempMaxi_write_1__SEL_5 =
	     WILL_FIRE_RL_compare_Stage_First && !preCom_F_D_OUT[33] &&
	     preCom_F_first__03_BITS_32_TO_1_14_ULT_tempMax_ETC___d122 ;
  assign MUX_tempMaxj_write_1__SEL_2 =
	     WILL_FIRE_RL_compare_Stage_Transition &&
	     (jCounter_Comp_41_EQ_numStates_4___d142 ||
	      preCom_F_first__03_BITS_32_TO_1_14_ULT_tempMax_ETC___d147) ;
  assign MUX_traceStage_State_write_1__SEL_1 =
	     EN_traceWrite_mav && countTime == 10'd1 ;
  assign MUX_traceStage_State_write_1__SEL_2 =
	     EN_outputPrint_mav && !valPrint_dreg && fPrint_dreg ;
  assign MUX_countTime_write_1__VAL_2 = countTime - 10'd1 ;
  assign MUX_countTime_write_1__VAL_3 = countTime + 10'd1 ;
  assign MUX_iCounter_Comp_write_1__VAL_2 =
	     iCounter_Comp_13_EQ_numStates_4___d117 ? 5'd1 : x__h4583 ;
  assign MUX_iCounter_stage1_write_1__VAL_2 =
	     iCounter_stage1_3_EQ_numStates_4___d35 ? 5'd1 : x__h2275 ;
  assign MUX_jCounter_Comp_write_1__VAL_2 =
	     jCounter_Comp_41_EQ_numStates_4___d142 ? 5'd1 : x__h4306 ;
  assign MUX_jCounter_stage1_write_1__VAL_2 =
	     jCounter_stage1_2_EQ_numStates_4___d57 ? 5'd1 : x__h2083 ;
  assign MUX_preAdd_F_enq_1__VAL_1 =
	     { preMem_F_D_OUT[22:20], 64'd0, preMem_F_D_OUT[0] } ;
  assign MUX_preAdd_F_enq_1__VAL_2 =
	     { preMem_F_D_OUT[22:20],
	       putMemVal_ma_d,
	       x__h6067,
	       preMem_F_D_OUT[0] } ;
  assign MUX_preMax_F_enq_1__VAL_1 =
	     { 1'd1,
	       iCounter_Comp,
	       preCom_F_first__03_BITS_32_TO_1_14_ULT_tempMax_ETC___d147 ?
		 preCom_F_D_OUT[32:1] :
		 tempMaxj[31:0] } ;
  assign MUX_preMax_F_enq_1__VAL_2 =
	     { preCom_F_D_OUT[33], iCounter_Comp, preCom_F_D_OUT[32:1] } ;
  assign MUX_preMax_F_enq_1__VAL_3 =
	     { 1'd0, iCounter_Comp, preCom_F_D_OUT[32:1] } ;
  assign MUX_preMem_F_enq_1__VAL_1 =
	     { 1'd1,
	       inpIsFirst_stage1,
	       emiss_stage1,
	       iCounter_stage1,
	       15'd0 } ;
  assign MUX_preMem_F_enq_1__VAL_2 =
	     { 2'd1,
	       emiss_stage1,
	       iCounter_stage1,
	       indfi__h1651,
	       op2fi__h1652,
	       1'd0 } ;
  assign MUX_preMem_F_enq_1__VAL_3 =
	     { 2'd0,
	       emiss_stage1,
	       iCounter_stage1,
	       xnt_memReq_op1_memIndex__h2060,
	       jCounter_stage1,
	       1'd0 } ;
  assign MUX_preMem_F_enq_1__VAL_4 =
	     { 2'd0,
	       emiss_stage1,
	       iCounter_stage1,
	       inp_F_D_OUT,
	       iCounter_stage1,
	       1'd0 } ;
  assign MUX_preTrace_F_enq_1__VAL_1 =
	     { 1'd0,
	       timeS,
	       iCounter_Comp_13_CONCAT_IF_preCom_F_first__03__ETC___d155 } ;
  assign MUX_preTrace_F_enq_1__VAL_2 = { 1'd0, timeS, 11'd1 } ;
  assign MUX_preTrace_F_enq_1__VAL_3 =
	     { 1'd1, trace_enq_timestep__h3593, tempMaxi[36:32], 6'd0 } ;
  assign MUX_tempMaxi_write_1__VAL_2 =
	     { iCounter_Comp, preCom_F_D_OUT[32:1] } ;
  assign MUX_tempMaxj_write_1__VAL_2 =
	     jCounter_Comp_41_EQ_numStates_4___d142 ?
	       37'h1FFFFFFFFF :
	       { jCounter_Comp, preCom_F_D_OUT[32:1] } ;
  assign MUX_timeS_write_1__VAL_2 = timeS + 10'd1 ;
  assign MUX_traceStage_State_write_1__VAL_3 =
	     (preTrace_F_D_OUT[20:11] == 10'd0) ? 2'd2 : 2'd0 ;

  // inlined wires
  assign clear_inter_stall_dly_1_wget =
	     MUX_clear_inter_stall_dly_1_wset_1__SEL_1 ||
	     MUX_clear_inter_stall_dly_1_wset_1__SEL_2 ;
  assign clear_inter_stall_dly_1_whas =
	     WILL_FIRE_RL_compare_Stage_First && preCom_F_D_OUT[33] &&
	     iCounter_Comp_13_EQ_numStates_4___d117 ||
	     WILL_FIRE_RL_compare_Stage_Transition &&
	     jCounter_Comp_41_EQ_numStates_4___d142 &&
	     iCounter_Comp_13_EQ_numStates_4___d117 ||
	     clear_inter_stall_dly ;
  assign clear_stall_dly_1_wget =
	     MUX_clear_stall_dly_1_wset_1__SEL_1 ||
	     MUX_clear_stall_dly_1_wset_1__SEL_2 ;
  assign clear_stall_dly_1_whas =
	     WILL_FIRE_RL_compare_Stage_Emission &&
	     iCounter_Comp_13_EQ_numStates_4___d117 ||
	     WILL_FIRE_RL_compare_Stage_First && !preCom_F_D_OUT[33] &&
	     iCounter_Comp_13_EQ_numStates_4___d117 ||
	     clear_stall_dly ;
  assign fPrint_dreg_1_whas = EN_outputPrint_mav && valPrint_dreg ;

  // register backTrackReg_0
  assign backTrackReg_0_D_IN =
	     MUX_backTrackReg_0_write_1__SEL_1 ?
	       preTrace_F_D_OUT[10:6] :
	       putBackTrack_ma_storedVal ;
  assign backTrackReg_0_EN =
	     WILL_FIRE_RL_trace_stage_endstore &&
	     preTrace_F_D_OUT[20:11] == 10'd0 ||
	     EN_putBackTrack_ma ;

  // register backTrackReg_1
  assign backTrackReg_1_D_IN =
	     MUX_backTrackReg_1_write_1__SEL_1 ?
	       preTrace_F_D_OUT[10:6] :
	       backTrackReg_0 ;
  assign backTrackReg_1_EN =
	     WILL_FIRE_RL_trace_stage_endstore &&
	     preTrace_F_D_OUT[20:11] != 10'd0 ||
	     EN_traceWrite_mav ;

  // register clear_inter_stall_dly
  assign clear_inter_stall_dly_D_IN =
	     clear_inter_stall_dly_1_whas && clear_inter_stall_dly_1_wget ;
  assign clear_inter_stall_dly_EN = 1'd1 ;

  // register clear_stall_dly
  assign clear_stall_dly_D_IN =
	     clear_stall_dly_1_whas && clear_stall_dly_1_wget ;
  assign clear_stall_dly_EN = 1'd1 ;

  // register countTime
  always@(MUX_backTrackReg_1_write_1__SEL_1 or
	  preTrace_F_D_OUT or
	  MUX_countTime_write_1__SEL_2 or
	  MUX_countTime_write_1__VAL_2 or
	  MUX_countTime_write_1__SEL_3 or MUX_countTime_write_1__VAL_3)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_backTrackReg_1_write_1__SEL_1:
	  countTime_D_IN = preTrace_F_D_OUT[20:11];
      MUX_countTime_write_1__SEL_2:
	  countTime_D_IN = MUX_countTime_write_1__VAL_2;
      MUX_countTime_write_1__SEL_3:
	  countTime_D_IN = MUX_countTime_write_1__VAL_3;
      default: countTime_D_IN = 10'bxxxxxxxxxx /* unspecified value */ ;
    endcase
  end
  assign countTime_EN =
	     WILL_FIRE_RL_trace_stage_endstore &&
	     preTrace_F_D_OUT[20:11] != 10'd0 ||
	     EN_traceWrite_mav && countTime != 10'd1 ||
	     EN_getBackTrack_mv &&
	     NOT_traceStage_State_28_EQ_0_11_13_OR_countTim_ETC___d221 ;

  // register done
  assign done_D_IN = !MUX_done_write_1__SEL_1 ;
  assign done_EN =
	     EN_outputPrint_mav && done ||
	     WILL_FIRE_RL_trace_stage_endstore &&
	     preTrace_F_D_OUT[20:11] == 10'd0 ||
	     EN_getBackTrack_mv &&
	     NOT_traceStage_State_28_EQ_0_11_13_OR_countTim_ETC___d219 ;

  // register emiss_stage1
  always@(EN_putInitial_ma or
	  MUX_emiss_stage1_write_1__SEL_2 or
	  emiss_stage1 or
	  MUX_emiss_stage1_write_1__SEL_3 or MUX_emiss_stage1_write_1__SEL_4)
  case (1'b1)
    EN_putInitial_ma: emiss_stage1_D_IN = 1'd1;
    MUX_emiss_stage1_write_1__SEL_2: emiss_stage1_D_IN = ~emiss_stage1;
    MUX_emiss_stage1_write_1__SEL_3: emiss_stage1_D_IN = ~emiss_stage1;
    MUX_emiss_stage1_write_1__SEL_4: emiss_stage1_D_IN = ~emiss_stage1;
    default: emiss_stage1_D_IN = 1'bx /* unspecified value */ ;
  endcase
  assign emiss_stage1_EN =
	     (WILL_FIRE_RL_stage_1_Normal_Emiss ||
	      WILL_FIRE_RL_stage_1_FirstInp) &&
	     iCounter_stage1_3_EQ_numStates_4___d35 ||
	     WILL_FIRE_RL_stage_1_Normal_Trans &&
	     jCounter_stage1_2_EQ_numStates_4___d57 &&
	     iCounter_stage1_3_EQ_numStates_4___d35 ||
	     EN_putInitial_ma ;

  // register fPrint_dreg
  assign fPrint_dreg_D_IN = fPrint_dreg_1_whas ;
  assign fPrint_dreg_EN = 1'd1 ;

  // register iCounter_Comp
  always@(EN_putInitial_ma or
	  WILL_FIRE_RL_compare_Stage_Emission or
	  MUX_iCounter_Comp_write_1__VAL_2 or
	  MUX_iCounter_Comp_write_1__SEL_3 or
	  WILL_FIRE_RL_compare_Stage_EndMarker or
	  WILL_FIRE_RL_compare_Stage_First)
  case (1'b1)
    EN_putInitial_ma: iCounter_Comp_D_IN = 5'd1;
    WILL_FIRE_RL_compare_Stage_Emission:
	iCounter_Comp_D_IN = MUX_iCounter_Comp_write_1__VAL_2;
    MUX_iCounter_Comp_write_1__SEL_3:
	iCounter_Comp_D_IN = MUX_iCounter_Comp_write_1__VAL_2;
    WILL_FIRE_RL_compare_Stage_EndMarker: iCounter_Comp_D_IN = 5'd1;
    WILL_FIRE_RL_compare_Stage_First:
	iCounter_Comp_D_IN = MUX_iCounter_Comp_write_1__VAL_2;
    default: iCounter_Comp_D_IN = 5'bxxxxx /* unspecified value */ ;
  endcase
  assign iCounter_Comp_EN =
	     WILL_FIRE_RL_compare_Stage_Transition &&
	     jCounter_Comp_41_EQ_numStates_4___d142 ||
	     WILL_FIRE_RL_compare_Stage_Emission ||
	     WILL_FIRE_RL_compare_Stage_First ||
	     WILL_FIRE_RL_compare_Stage_EndMarker ||
	     EN_putInitial_ma ;

  // register iCounter_stage1
  always@(EN_putInitial_ma or
	  WILL_FIRE_RL_stage_1_Normal_Emiss or
	  MUX_iCounter_stage1_write_1__VAL_2 or
	  MUX_iCounter_stage1_write_1__SEL_3 or WILL_FIRE_RL_stage_1_FirstInp)
  case (1'b1)
    EN_putInitial_ma: iCounter_stage1_D_IN = 5'd1;
    WILL_FIRE_RL_stage_1_Normal_Emiss:
	iCounter_stage1_D_IN = MUX_iCounter_stage1_write_1__VAL_2;
    MUX_iCounter_stage1_write_1__SEL_3:
	iCounter_stage1_D_IN = MUX_iCounter_stage1_write_1__VAL_2;
    WILL_FIRE_RL_stage_1_FirstInp:
	iCounter_stage1_D_IN = MUX_iCounter_stage1_write_1__VAL_2;
    default: iCounter_stage1_D_IN = 5'bxxxxx /* unspecified value */ ;
  endcase
  assign iCounter_stage1_EN =
	     WILL_FIRE_RL_stage_1_Normal_Trans &&
	     jCounter_stage1_2_EQ_numStates_4___d57 ||
	     WILL_FIRE_RL_stage_1_Normal_Emiss ||
	     WILL_FIRE_RL_stage_1_FirstInp ||
	     EN_putInitial_ma ;

  // register index
  always@(MUX_index_write_1__SEL_1 or
	  WILL_FIRE_RL_trace_stage_endstore or
	  preTrace_F_D_OUT or
	  EN_traceWrite_mav or countTime or EN_getBackTrack_mv)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_index_write_1__SEL_1: index_D_IN = 1'd0;
      WILL_FIRE_RL_trace_stage_endstore:
	  index_D_IN = preTrace_F_D_OUT[20:11] == 10'd0;
      EN_traceWrite_mav: index_D_IN = countTime == 10'd1;
      EN_getBackTrack_mv: index_D_IN = 1'd1;
      default: index_D_IN = 1'bx /* unspecified value */ ;
    endcase
  end
  assign index_EN =
	     EN_outputPrint_mav && !valPrint_dreg && !fPrint_dreg && !done ||
	     WILL_FIRE_RL_trace_stage_endstore ||
	     EN_traceWrite_mav ||
	     EN_getBackTrack_mv ;

  // register inpIsFirst_stage1
  assign inpIsFirst_stage1_D_IN = !MUX_inpIsFirst_stage1_write_1__SEL_1 ;
  assign inpIsFirst_stage1_EN =
	     WILL_FIRE_RL_stage_1_FirstInp &&
	     iCounter_stage1_3_EQ_numStates_4___d35 &&
	     !emiss_stage1 ||
	     WILL_FIRE_RL_stage_1_Endmark ||
	     EN_putInitial_ma ;

  // register jCounter_Comp
  always@(EN_putInitial_ma or
	  WILL_FIRE_RL_compare_Stage_Transition or
	  MUX_jCounter_Comp_write_1__VAL_2 or
	  WILL_FIRE_RL_compare_Stage_EndMarker)
  case (1'b1)
    EN_putInitial_ma: jCounter_Comp_D_IN = 5'd1;
    WILL_FIRE_RL_compare_Stage_Transition:
	jCounter_Comp_D_IN = MUX_jCounter_Comp_write_1__VAL_2;
    WILL_FIRE_RL_compare_Stage_EndMarker: jCounter_Comp_D_IN = 5'd1;
    default: jCounter_Comp_D_IN = 5'bxxxxx /* unspecified value */ ;
  endcase
  assign jCounter_Comp_EN =
	     WILL_FIRE_RL_compare_Stage_Transition ||
	     WILL_FIRE_RL_compare_Stage_EndMarker ||
	     EN_putInitial_ma ;

  // register jCounter_stage1
  assign jCounter_stage1_D_IN =
	     EN_putInitial_ma ? 5'd1 : MUX_jCounter_stage1_write_1__VAL_2 ;
  assign jCounter_stage1_EN =
	     WILL_FIRE_RL_stage_1_Normal_Trans || EN_putInitial_ma ;

  // register numObs
  assign numObs_D_IN = putInitial_ma_m[8:0] ;
  assign numObs_EN = EN_putInitial_ma ;

  // register numStates
  assign numStates_D_IN = putInitial_ma_n[4:0] ;
  assign numStates_EN = EN_putInitial_ma ;

  // register tempMaxi
  always@(EN_putInitial_ma or
	  MUX_tempMaxi_write_1__SEL_2 or
	  MUX_tempMaxi_write_1__VAL_2 or
	  MUX_clear_inter_stall_dly_1_wset_1__SEL_1 or
	  WILL_FIRE_RL_compare_Stage_EndMarker or MUX_tempMaxi_write_1__SEL_5)
  case (1'b1)
    EN_putInitial_ma: tempMaxi_D_IN = 37'h1FFFFFFFFF;
    MUX_tempMaxi_write_1__SEL_2: tempMaxi_D_IN = MUX_tempMaxi_write_1__VAL_2;
    MUX_clear_inter_stall_dly_1_wset_1__SEL_1 ||
    WILL_FIRE_RL_compare_Stage_EndMarker:
	tempMaxi_D_IN = 37'h1FFFFFFFFF;
    MUX_tempMaxi_write_1__SEL_5: tempMaxi_D_IN = MUX_tempMaxi_write_1__VAL_2;
    default: tempMaxi_D_IN =
		 37'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
  endcase
  assign tempMaxi_EN =
	     WILL_FIRE_RL_compare_Stage_Emission &&
	     preCom_F_first__03_BITS_32_TO_1_14_ULT_tempMax_ETC___d122 ||
	     WILL_FIRE_RL_compare_Stage_First && !preCom_F_D_OUT[33] &&
	     preCom_F_first__03_BITS_32_TO_1_14_ULT_tempMax_ETC___d122 ||
	     WILL_FIRE_RL_compare_Stage_Transition &&
	     jCounter_Comp_41_EQ_numStates_4___d142 &&
	     iCounter_Comp_13_EQ_numStates_4___d117 ||
	     WILL_FIRE_RL_compare_Stage_EndMarker ||
	     EN_putInitial_ma ;

  // register tempMaxj
  always@(EN_putInitial_ma or
	  MUX_tempMaxj_write_1__SEL_2 or
	  MUX_tempMaxj_write_1__VAL_2 or WILL_FIRE_RL_compare_Stage_EndMarker)
  case (1'b1)
    EN_putInitial_ma: tempMaxj_D_IN = 37'h1FFFFFFFFF;
    MUX_tempMaxj_write_1__SEL_2: tempMaxj_D_IN = MUX_tempMaxj_write_1__VAL_2;
    WILL_FIRE_RL_compare_Stage_EndMarker: tempMaxj_D_IN = 37'h1FFFFFFFFF;
    default: tempMaxj_D_IN =
		 37'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
  endcase
  assign tempMaxj_EN =
	     WILL_FIRE_RL_compare_Stage_Transition &&
	     (jCounter_Comp_41_EQ_numStates_4___d142 ||
	      preCom_F_first__03_BITS_32_TO_1_14_ULT_tempMax_ETC___d147) ||
	     WILL_FIRE_RL_compare_Stage_EndMarker ||
	     EN_putInitial_ma ;

  // register timeS
  always@(EN_putInitial_ma or
	  MUX_clear_stall_dly_1_wset_1__SEL_1 or
	  MUX_timeS_write_1__VAL_2 or WILL_FIRE_RL_compare_Stage_EndMarker)
  case (1'b1)
    EN_putInitial_ma: timeS_D_IN = 10'd1;
    MUX_clear_stall_dly_1_wset_1__SEL_1:
	timeS_D_IN = MUX_timeS_write_1__VAL_2;
    WILL_FIRE_RL_compare_Stage_EndMarker: timeS_D_IN = 10'd1;
    default: timeS_D_IN = 10'bxxxxxxxxxx /* unspecified value */ ;
  endcase
  assign timeS_EN =
	     WILL_FIRE_RL_compare_Stage_Emission &&
	     iCounter_Comp_13_EQ_numStates_4___d117 ||
	     WILL_FIRE_RL_compare_Stage_EndMarker ||
	     EN_putInitial_ma ;

  // register timeTotal
  assign timeTotal_D_IN = preTrace_F_D_OUT[20:11] ;
  assign timeTotal_EN = MUX_backTrackReg_1_write_1__SEL_1 ;

  // register traceStage_State
  always@(MUX_traceStage_State_write_1__SEL_1 or
	  MUX_traceStage_State_write_1__SEL_2 or
	  WILL_FIRE_RL_trace_stage_endstore or
	  MUX_traceStage_State_write_1__VAL_3)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_traceStage_State_write_1__SEL_1: traceStage_State_D_IN = 2'd2;
      MUX_traceStage_State_write_1__SEL_2: traceStage_State_D_IN = 2'd1;
      WILL_FIRE_RL_trace_stage_endstore:
	  traceStage_State_D_IN = MUX_traceStage_State_write_1__VAL_3;
      default: traceStage_State_D_IN = 2'bxx /* unspecified value */ ;
    endcase
  end
  assign traceStage_State_EN =
	     EN_traceWrite_mav && countTime == 10'd1 ||
	     EN_outputPrint_mav && !valPrint_dreg && fPrint_dreg ||
	     WILL_FIRE_RL_trace_stage_endstore ;

  // register valOut
  assign valOut_D_IN = tempMaxi[31:0] ;
  assign valOut_EN = WILL_FIRE_RL_compare_Stage_EndMarker ;

  // register valPrint_dreg
  assign valPrint_dreg_D_IN = MUX_done_write_1__SEL_1 ;
  assign valPrint_dreg_EN = 1'd1 ;

  // register viterbiState
  assign viterbiState_D_IN = EN_putInitial_ma ? 2'd1 : 2'd2 ;
  assign viterbiState_EN = EN_putInitial_ma || WILL_FIRE_RL_stage_1_zero ;

  // register vt_inter_is_ready
  assign vt_inter_is_ready_D_IN = clear_inter_stall_dly ;
  assign vt_inter_is_ready_EN =
	     WILL_FIRE_RL_stage_1_FirstInp &&
	     iCounter_stage1_3_EQ_numStates_4___d35 &&
	     emiss_stage1 ||
	     WILL_FIRE_RL_stage_1_Normal_Trans &&
	     jCounter_stage1_2_EQ_numStates_4___d57 &&
	     iCounter_stage1_3_EQ_numStates_4___d35 ||
	     clear_inter_stall_dly ;

  // register vt_is_ready
  assign vt_is_ready_D_IN = clear_stall_dly ;
  assign vt_is_ready_EN =
	     WILL_FIRE_RL_stage_1_Normal_Emiss &&
	     iCounter_stage1_3_EQ_numStates_4___d35 ||
	     WILL_FIRE_RL_stage_1_FirstInp &&
	     iCounter_stage1_3_EQ_numStates_4___d35 &&
	     !emiss_stage1 ||
	     clear_stall_dly ;

  // submodule fpadder
  assign fpadder_put_a = preAdd_F_D_OUT[64:33] ;
  assign fpadder_put_b = preAdd_F_D_OUT[32:1] ;
  assign fpadder_EN_put = CAN_FIRE_RL_feed_adder_stage1 ;
  assign fpadder_EN_get = CAN_FIRE_RL_retrieve_from_adder_stage2 ;

  // submodule inp_F
  assign inp_F_D_IN = putInpVal_ma_in[8:0] ;
  assign inp_F_ENQ = EN_putInpVal_ma ;
  assign inp_F_DEQ =
	     WILL_FIRE_RL_stage_1_Normal_Emiss &&
	     iCounter_stage1_3_EQ_numStates_4___d35 ||
	     WILL_FIRE_RL_stage_1_FirstInp &&
	     iCounter_stage1_3_EQ_numStates_4___d35 &&
	     !emiss_stage1 ||
	     WILL_FIRE_RL_stage_1_Endmark ;
  assign inp_F_CLR = 1'b0 ;

  // submodule metadata_fifo
  assign metadata_fifo_D_IN = { preAdd_F_D_OUT[67:65], preAdd_F_D_OUT[0] } ;
  assign metadata_fifo_ENQ = CAN_FIRE_RL_feed_adder_stage1 ;
  assign metadata_fifo_DEQ = CAN_FIRE_RL_retrieve_from_adder_stage2 ;
  assign metadata_fifo_CLR = 1'b0 ;

  // submodule preAdd_F
  assign preAdd_F_D_IN =
	     WILL_FIRE_RL_memEnd_handle ?
	       MUX_preAdd_F_enq_1__VAL_1 :
	       MUX_preAdd_F_enq_1__VAL_2 ;
  assign preAdd_F_ENQ = WILL_FIRE_RL_memEnd_handle || EN_putMemVal_ma ;
  assign preAdd_F_DEQ = CAN_FIRE_RL_feed_adder_stage1 ;
  assign preAdd_F_CLR = 1'b0 ;

  // submodule preCom_F
  assign preCom_F_D_IN =
	     { metadata_fifo_D_OUT[3:1],
	       fpadder_get,
	       metadata_fifo_D_OUT[0] } ;
  assign preCom_F_ENQ = CAN_FIRE_RL_retrieve_from_adder_stage2 ;
  assign preCom_F_DEQ =
	     WILL_FIRE_RL_compare_Stage_Transition ||
	     WILL_FIRE_RL_compare_Stage_Emission ||
	     WILL_FIRE_RL_compare_Stage_First ||
	     WILL_FIRE_RL_compare_Stage_EndMarker ||
	     WILL_FIRE_RL_compare_stage_zero ;
  assign preCom_F_CLR = 1'b0 ;

  // submodule preMax_F
  always@(MUX_iCounter_Comp_write_1__SEL_3 or
	  MUX_preMax_F_enq_1__VAL_1 or
	  WILL_FIRE_RL_compare_Stage_First or
	  MUX_preMax_F_enq_1__VAL_2 or
	  WILL_FIRE_RL_compare_Stage_Emission or MUX_preMax_F_enq_1__VAL_3)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_iCounter_Comp_write_1__SEL_3:
	  preMax_F_D_IN = MUX_preMax_F_enq_1__VAL_1;
      WILL_FIRE_RL_compare_Stage_First:
	  preMax_F_D_IN = MUX_preMax_F_enq_1__VAL_2;
      WILL_FIRE_RL_compare_Stage_Emission:
	  preMax_F_D_IN = MUX_preMax_F_enq_1__VAL_3;
      default: preMax_F_D_IN =
		   38'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
    endcase
  end
  assign preMax_F_ENQ =
	     WILL_FIRE_RL_compare_Stage_Transition &&
	     jCounter_Comp_41_EQ_numStates_4___d142 ||
	     WILL_FIRE_RL_compare_Stage_First ||
	     WILL_FIRE_RL_compare_Stage_Emission ;
  assign preMax_F_DEQ = EN_maxStore ;
  assign preMax_F_CLR = 1'b0 ;

  // submodule preMem_F
  always@(WILL_FIRE_RL_stage_1_Endmark or
	  MUX_preMem_F_enq_1__VAL_1 or
	  WILL_FIRE_RL_stage_1_FirstInp or
	  MUX_preMem_F_enq_1__VAL_2 or
	  WILL_FIRE_RL_stage_1_Normal_Trans or
	  MUX_preMem_F_enq_1__VAL_3 or
	  WILL_FIRE_RL_stage_1_Normal_Emiss or
	  MUX_preMem_F_enq_1__VAL_4 or WILL_FIRE_RL_stage_1_zero)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_stage_1_Endmark: preMem_F_D_IN = MUX_preMem_F_enq_1__VAL_1;
      WILL_FIRE_RL_stage_1_FirstInp:
	  preMem_F_D_IN = MUX_preMem_F_enq_1__VAL_2;
      WILL_FIRE_RL_stage_1_Normal_Trans:
	  preMem_F_D_IN = MUX_preMem_F_enq_1__VAL_3;
      WILL_FIRE_RL_stage_1_Normal_Emiss:
	  preMem_F_D_IN = MUX_preMem_F_enq_1__VAL_4;
      WILL_FIRE_RL_stage_1_zero: preMem_F_D_IN = 23'd1;
      default: preMem_F_D_IN =
		   23'bxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
    endcase
  end
  assign preMem_F_ENQ =
	     WILL_FIRE_RL_stage_1_Endmark || WILL_FIRE_RL_stage_1_FirstInp ||
	     WILL_FIRE_RL_stage_1_Normal_Trans ||
	     WILL_FIRE_RL_stage_1_Normal_Emiss ||
	     WILL_FIRE_RL_stage_1_zero ;
  assign preMem_F_DEQ = WILL_FIRE_RL_memEnd_handle || EN_putMemVal_ma ;
  assign preMem_F_CLR = 1'b0 ;

  // submodule preTrace_F
  always@(MUX_iCounter_Comp_write_1__SEL_3 or
	  MUX_preTrace_F_enq_1__VAL_1 or
	  WILL_FIRE_RL_compare_stage_zero or
	  MUX_preTrace_F_enq_1__VAL_2 or
	  WILL_FIRE_RL_compare_Stage_EndMarker or MUX_preTrace_F_enq_1__VAL_3)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_iCounter_Comp_write_1__SEL_3:
	  preTrace_F_D_IN = MUX_preTrace_F_enq_1__VAL_1;
      WILL_FIRE_RL_compare_stage_zero:
	  preTrace_F_D_IN = MUX_preTrace_F_enq_1__VAL_2;
      WILL_FIRE_RL_compare_Stage_EndMarker:
	  preTrace_F_D_IN = MUX_preTrace_F_enq_1__VAL_3;
      default: preTrace_F_D_IN =
		   22'bxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
    endcase
  end
  assign preTrace_F_ENQ =
	     WILL_FIRE_RL_compare_Stage_Transition &&
	     jCounter_Comp_41_EQ_numStates_4___d142 ||
	     WILL_FIRE_RL_compare_stage_zero ||
	     WILL_FIRE_RL_compare_Stage_EndMarker ;
  assign preTrace_F_DEQ =
	     WILL_FIRE_RL_trace_stage_endstore || EN_outputPrint0_mav ||
	     EN_traceStore_mav ;
  assign preTrace_F_CLR = 1'b0 ;

  // remaining internal signals
  assign NOT_traceStage_State_28_EQ_0_11_13_OR_countTim_ETC___d219 =
	     (traceStage_State != 2'd0 || countTime == 10'd0 || index) &&
	     countTime_06_EQ_timeTotal_17___d218 ;
  assign NOT_traceStage_State_28_EQ_0_11_13_OR_countTim_ETC___d221 =
	     (traceStage_State != 2'd0 || countTime == 10'd0 || index) &&
	     !countTime_06_EQ_timeTotal_17___d218 ;
  assign countTime_06_EQ_timeTotal_17___d218 = countTime == timeTotal ;
  assign iCounter_Comp_13_CONCAT_IF_preCom_F_first__03__ETC___d155 =
	     { iCounter_Comp,
	       preCom_F_first__03_BITS_32_TO_1_14_ULT_tempMax_ETC___d147 ?
		 jCounter_Comp :
		 tempMaxj[36:32],
	       1'd0 } ;
  assign iCounter_Comp_13_EQ_numStates_4___d117 = iCounter_Comp == numStates ;
  assign iCounter_stage1_3_EQ_numStates_4___d35 =
	     iCounter_stage1 == numStates ;
  assign indfi__h1651 = emiss_stage1 ? 9'b0 : inp_F_D_OUT ;
  assign inpIsFirst_stage1_1_AND_viterbiState_0_EQ_1_1__ETC___d32 =
	     inpIsFirst_stage1 && viterbiState == 2'd1 &&
	     inp_F_D_OUT != 9'd0 &&
	     (emiss_stage1 || vt_inter_is_ready) ;
  assign jCounter_Comp_41_EQ_numStates_4___d142 = jCounter_Comp == numStates ;
  assign jCounter_stage1_2_EQ_numStates_4___d57 =
	     jCounter_stage1 == numStates ;
  assign op2fi__h1652 = emiss_stage1 ? 5'b0 : iCounter_stage1 ;
  assign preCom_F_first__03_BITS_32_TO_1_14_ULT_tempMax_ETC___d122 =
	     preCom_F_D_OUT[32:1] < tempMaxi[31:0] ;
  assign preCom_F_first__03_BITS_32_TO_1_14_ULT_tempMax_ETC___d147 =
	     preCom_F_D_OUT[32:1] < tempMaxj[31:0] ;
  assign trace_enq_timestep__h3593 = timeS - 10'd1 ;
  assign v__h6852 = fPrint_dreg ? 32'hFFFFFFFF : v__h6901 ;
  assign v__h6901 = { 27'b0, backTrackReg_0 } ;
  assign x__h2083 = jCounter_stage1 + 5'd1 ;
  assign x__h2275 = iCounter_stage1 + 5'd1 ;
  assign x__h4306 = jCounter_Comp + 5'd1 ;
  assign x__h4583 = iCounter_Comp + 5'd1 ;
  assign x__h6067 =
	     (preMem_F_D_OUT[21] && preMem_F_D_OUT[20]) ?
	       32'd0 :
	       putMemVal_ma_d1 ;
  assign x__h6676 =
	     (traceStage_State == 2'd0 && countTime != 10'd0 && !index) ?
	       backTrackReg_1 :
	       5'd1 ;
  assign xnt_memReq_op1_memIndex__h2060 = { 4'd0, jCounter_stage1 } ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        backTrackReg_0 <= `BSV_ASSIGNMENT_DELAY 5'd0;
	backTrackReg_1 <= `BSV_ASSIGNMENT_DELAY 5'd0;
	clear_inter_stall_dly <= `BSV_ASSIGNMENT_DELAY 1'd0;
	clear_stall_dly <= `BSV_ASSIGNMENT_DELAY 1'd0;
	countTime <= `BSV_ASSIGNMENT_DELAY 10'd0;
	done <= `BSV_ASSIGNMENT_DELAY 1'd0;
	emiss_stage1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	fPrint_dreg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	iCounter_Comp <= `BSV_ASSIGNMENT_DELAY 5'd1;
	iCounter_stage1 <= `BSV_ASSIGNMENT_DELAY 5'd1;
	index <= `BSV_ASSIGNMENT_DELAY 1'd0;
	inpIsFirst_stage1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	jCounter_Comp <= `BSV_ASSIGNMENT_DELAY 5'd1;
	jCounter_stage1 <= `BSV_ASSIGNMENT_DELAY 5'd1;
	numObs <= `BSV_ASSIGNMENT_DELAY 9'd0;
	numStates <= `BSV_ASSIGNMENT_DELAY 5'd0;
	tempMaxi <= `BSV_ASSIGNMENT_DELAY 37'h1FFFFFFFFF;
	tempMaxj <= `BSV_ASSIGNMENT_DELAY 37'h1FFFFFFFFF;
	timeS <= `BSV_ASSIGNMENT_DELAY 10'd1;
	timeTotal <= `BSV_ASSIGNMENT_DELAY 10'd0;
	traceStage_State <= `BSV_ASSIGNMENT_DELAY 2'd1;
	valOut <= `BSV_ASSIGNMENT_DELAY 32'd0;
	valPrint_dreg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	viterbiState <= `BSV_ASSIGNMENT_DELAY 2'd0;
	vt_inter_is_ready <= `BSV_ASSIGNMENT_DELAY 1'd1;
	vt_is_ready <= `BSV_ASSIGNMENT_DELAY 1'd1;
      end
    else
      begin
        if (backTrackReg_0_EN)
	  backTrackReg_0 <= `BSV_ASSIGNMENT_DELAY backTrackReg_0_D_IN;
	if (backTrackReg_1_EN)
	  backTrackReg_1 <= `BSV_ASSIGNMENT_DELAY backTrackReg_1_D_IN;
	if (clear_inter_stall_dly_EN)
	  clear_inter_stall_dly <= `BSV_ASSIGNMENT_DELAY
	      clear_inter_stall_dly_D_IN;
	if (clear_stall_dly_EN)
	  clear_stall_dly <= `BSV_ASSIGNMENT_DELAY clear_stall_dly_D_IN;
	if (countTime_EN) countTime <= `BSV_ASSIGNMENT_DELAY countTime_D_IN;
	if (done_EN) done <= `BSV_ASSIGNMENT_DELAY done_D_IN;
	if (emiss_stage1_EN)
	  emiss_stage1 <= `BSV_ASSIGNMENT_DELAY emiss_stage1_D_IN;
	if (fPrint_dreg_EN)
	  fPrint_dreg <= `BSV_ASSIGNMENT_DELAY fPrint_dreg_D_IN;
	if (iCounter_Comp_EN)
	  iCounter_Comp <= `BSV_ASSIGNMENT_DELAY iCounter_Comp_D_IN;
	if (iCounter_stage1_EN)
	  iCounter_stage1 <= `BSV_ASSIGNMENT_DELAY iCounter_stage1_D_IN;
	if (index_EN) index <= `BSV_ASSIGNMENT_DELAY index_D_IN;
	if (inpIsFirst_stage1_EN)
	  inpIsFirst_stage1 <= `BSV_ASSIGNMENT_DELAY inpIsFirst_stage1_D_IN;
	if (jCounter_Comp_EN)
	  jCounter_Comp <= `BSV_ASSIGNMENT_DELAY jCounter_Comp_D_IN;
	if (jCounter_stage1_EN)
	  jCounter_stage1 <= `BSV_ASSIGNMENT_DELAY jCounter_stage1_D_IN;
	if (numObs_EN) numObs <= `BSV_ASSIGNMENT_DELAY numObs_D_IN;
	if (numStates_EN) numStates <= `BSV_ASSIGNMENT_DELAY numStates_D_IN;
	if (tempMaxi_EN) tempMaxi <= `BSV_ASSIGNMENT_DELAY tempMaxi_D_IN;
	if (tempMaxj_EN) tempMaxj <= `BSV_ASSIGNMENT_DELAY tempMaxj_D_IN;
	if (timeS_EN) timeS <= `BSV_ASSIGNMENT_DELAY timeS_D_IN;
	if (timeTotal_EN) timeTotal <= `BSV_ASSIGNMENT_DELAY timeTotal_D_IN;
	if (traceStage_State_EN)
	  traceStage_State <= `BSV_ASSIGNMENT_DELAY traceStage_State_D_IN;
	if (valOut_EN) valOut <= `BSV_ASSIGNMENT_DELAY valOut_D_IN;
	if (valPrint_dreg_EN)
	  valPrint_dreg <= `BSV_ASSIGNMENT_DELAY valPrint_dreg_D_IN;
	if (viterbiState_EN)
	  viterbiState <= `BSV_ASSIGNMENT_DELAY viterbiState_D_IN;
	if (vt_inter_is_ready_EN)
	  vt_inter_is_ready <= `BSV_ASSIGNMENT_DELAY vt_inter_is_ready_D_IN;
	if (vt_is_ready_EN)
	  vt_is_ready <= `BSV_ASSIGNMENT_DELAY vt_is_ready_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    backTrackReg_0 = 5'h0A;
    backTrackReg_1 = 5'h0A;
    clear_inter_stall_dly = 1'h0;
    clear_stall_dly = 1'h0;
    countTime = 10'h2AA;
    done = 1'h0;
    emiss_stage1 = 1'h0;
    fPrint_dreg = 1'h0;
    iCounter_Comp = 5'h0A;
    iCounter_stage1 = 5'h0A;
    index = 1'h0;
    inpIsFirst_stage1 = 1'h0;
    jCounter_Comp = 5'h0A;
    jCounter_stage1 = 5'h0A;
    numObs = 9'h0AA;
    numStates = 5'h0A;
    tempMaxi = 37'h0AAAAAAAAA;
    tempMaxj = 37'h0AAAAAAAAA;
    timeS = 10'h2AA;
    timeTotal = 10'h2AA;
    traceStage_State = 2'h2;
    valOut = 32'hAAAAAAAA;
    valPrint_dreg = 1'h0;
    viterbiState = 2'h2;
    vt_inter_is_ready = 1'h0;
    vt_is_ready = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1_zero)
	begin
	  v__h1418 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1_zero)
	$display(v__h1418,
		 " DEBUG: RULE stage_1_zero fired. Input is zero. Setting state to ZERO.");
  end
  // synopsys translate_on
endmodule  // mkdut

