//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Wed Nov 12 22:15:14 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// RDY_put                        O     1 reg
// get                            O    32
// RDY_get                        O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// put_a                          I    32
// put_b                          I    32
// EN_put                         I     1
// EN_get                         I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFPadder32(CLK,
		   RST_N,

		   put_a,
		   put_b,
		   EN_put,
		   RDY_put,

		   EN_get,
		   get,
		   RDY_get);
  input  CLK;
  input  RST_N;

  // action method put
  input  [31 : 0] put_a;
  input  [31 : 0] put_b;
  input  EN_put;
  output RDY_put;

  // actionvalue method get
  input  EN_get;
  output [31 : 0] get;
  output RDY_get;

  // signals for module outputs
  wire [31 : 0] get;
  wire RDY_get, RDY_put;

  // inlined wires
  wire [32 : 0] result_fifo_rv_port0__write_1,
		result_fifo_rv_port1__read,
		result_fifo_rv_port1__write_1,
		result_fifo_rv_port2__read;

  // register result_fifo_rv
  reg [32 : 0] result_fifo_rv;
  wire [32 : 0] result_fifo_rv_D_IN;
  wire result_fifo_rv_EN;

  // ports of submodule s1_to_s2_fifo
  wire [37 : 0] s1_to_s2_fifo_D_IN, s1_to_s2_fifo_D_OUT;
  wire s1_to_s2_fifo_CLR,
       s1_to_s2_fifo_DEQ,
       s1_to_s2_fifo_EMPTY_N,
       s1_to_s2_fifo_ENQ,
       s1_to_s2_fifo_FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_process_stage2,
       CAN_FIRE_get,
       CAN_FIRE_put,
       WILL_FIRE_RL_process_stage2,
       WILL_FIRE_get,
       WILL_FIRE_put;

  // remaining internal signals
  wire [30 : 0] IF_0_CONCAT_IF_s1_to_s2_fifo_first_BIT_28_THEN_ETC___d41;
  wire [27 : 0] IF_x723_BIT_0_XOR_x871_BIT_0_THEN_1_ELSE_0__q1, mantSum__h976;
  wire [26 : 0] _0b1_CONCAT_put_a_BITS_22_TO_0_9_CONCAT_0b0_0_S_ETC___d52,
		_0b1_CONCAT_put_b_BITS_22_TO_0_4_CONCAT_0b0_5_S_ETC___d67,
		_theResult___snd_snd__h1729,
		_theResult___snd_snd__h1872,
		mantA__h970,
		mantB__h971,
		x__h1723,
		x__h1784,
		x__h1871,
		x__h1928,
		y__h1795,
		y__h1939;
  wire [25 : 0] IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d277;
  wire [24 : 0] _0_CONCAT_IF_s1_to_s2_fifo_first_BIT_28_THEN_s1_ETC___d27;
  wire [23 : 0] IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d276,
		sig24__h512;
  wire [22 : 0] _theResult_____1_snd__h855;
  wire [21 : 0] IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d275;
  wire [19 : 0] IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d274;
  wire [17 : 0] IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d273;
  wire [15 : 0] IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d272;
  wire [13 : 0] IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d271;
  wire [11 : 0] IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d270;
  wire [9 : 0] IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d269;
  wire [7 : 0] IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d268,
	       _theResult_____1_fst__h854,
	       expCommon__h974,
	       expDiff__h1014,
	       expDiff__h1019,
	       incrementedExp__h839,
	       newExp___1__h584;
  wire [5 : 0] IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d267;
  wire [3 : 0] IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d266;
  wire [1 : 0] IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d265;
  wire put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO_23_6___d47,
       sticky__h1015,
       sticky__h1020,
       x__h2032,
       x__h2130,
       x__h2183,
       x__h2228,
       x__h2281,
       x__h2326,
       x__h2379,
       x__h2424,
       x__h2477,
       x__h2522,
       x__h2575,
       x__h2620,
       x__h2673,
       x__h2718,
       x__h2771,
       x__h2816,
       x__h2869,
       x__h2914,
       x__h2967,
       x__h3012,
       x__h3065,
       x__h3110,
       x__h3163,
       x__h3208,
       x__h3261,
       x__h3306,
       x__h3359,
       x__h3404,
       x__h3457,
       x__h3502,
       x__h3555,
       x__h3600,
       x__h3653,
       x__h3698,
       x__h3751,
       x__h3796,
       x__h3849,
       x__h3894,
       x__h3947,
       x__h3992,
       x__h4045,
       x__h4090,
       x__h4143,
       x__h4188,
       x__h4241,
       x__h4286,
       x__h4339,
       x__h4384,
       x__h4437,
       x__h4482,
       x__h4535,
       x__h4633,
       y__h2033,
       y__h2131,
       y__h2184,
       y__h2229,
       y__h2282,
       y__h2327,
       y__h2380,
       y__h2425,
       y__h2478,
       y__h2523,
       y__h2576,
       y__h2621,
       y__h2674,
       y__h2719,
       y__h2772,
       y__h2817,
       y__h2870,
       y__h2915,
       y__h2968,
       y__h3013,
       y__h3066,
       y__h3111,
       y__h3164,
       y__h3209,
       y__h3262,
       y__h3307,
       y__h3360,
       y__h3405,
       y__h3458,
       y__h3503,
       y__h3556,
       y__h3601,
       y__h3654,
       y__h3699,
       y__h3752,
       y__h3797,
       y__h3850,
       y__h3895,
       y__h3948,
       y__h3993,
       y__h4046,
       y__h4091,
       y__h4144,
       y__h4189,
       y__h4242,
       y__h4287,
       y__h4340,
       y__h4385,
       y__h4438,
       y__h4483,
       y__h4536,
       y__h4634;

  // action method put
  assign RDY_put = s1_to_s2_fifo_FULL_N ;
  assign CAN_FIRE_put = s1_to_s2_fifo_FULL_N ;
  assign WILL_FIRE_put = EN_put ;

  // actionvalue method get
  assign get = result_fifo_rv_port1__read[31:0] ;
  assign RDY_get = result_fifo_rv_port1__read[32] ;
  assign CAN_FIRE_get = result_fifo_rv_port1__read[32] ;
  assign WILL_FIRE_get = EN_get ;

  // submodule s1_to_s2_fifo
  FIFO2 #(.width(32'd38), .guarded(1'd1)) s1_to_s2_fifo(.RST(RST_N),
							.CLK(CLK),
							.D_IN(s1_to_s2_fifo_D_IN),
							.ENQ(s1_to_s2_fifo_ENQ),
							.DEQ(s1_to_s2_fifo_DEQ),
							.CLR(s1_to_s2_fifo_CLR),
							.D_OUT(s1_to_s2_fifo_D_OUT),
							.FULL_N(s1_to_s2_fifo_FULL_N),
							.EMPTY_N(s1_to_s2_fifo_EMPTY_N));

  // rule RL_process_stage2
  assign CAN_FIRE_RL_process_stage2 =
	     s1_to_s2_fifo_EMPTY_N && !result_fifo_rv[32] ;
  assign WILL_FIRE_RL_process_stage2 = CAN_FIRE_RL_process_stage2 ;

  // inlined wires
  assign result_fifo_rv_port0__write_1 =
	     { 1'd1,
	       s1_to_s2_fifo_D_OUT[37],
	       s1_to_s2_fifo_D_OUT[0] ?
		 31'h7F800000 :
		 IF_0_CONCAT_IF_s1_to_s2_fifo_first_BIT_28_THEN_ETC___d41 } ;
  assign result_fifo_rv_port1__read =
	     CAN_FIRE_RL_process_stage2 ?
	       result_fifo_rv_port0__write_1 :
	       result_fifo_rv ;
  assign result_fifo_rv_port1__write_1 =
	     { 1'd0,
	       32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign result_fifo_rv_port2__read =
	     EN_get ?
	       result_fifo_rv_port1__write_1 :
	       result_fifo_rv_port1__read ;

  // register result_fifo_rv
  assign result_fifo_rv_D_IN = result_fifo_rv_port2__read ;
  assign result_fifo_rv_EN = 1'b1 ;

  // submodule s1_to_s2_fifo
  assign s1_to_s2_fifo_D_IN =
	     { put_a[31],
	       expCommon__h974,
	       mantSum__h976,
	       expCommon__h974 == 8'hFF } ;
  assign s1_to_s2_fifo_ENQ = EN_put ;
  assign s1_to_s2_fifo_DEQ = CAN_FIRE_RL_process_stage2 ;
  assign s1_to_s2_fifo_CLR = 1'b0 ;

  // remaining internal signals
  assign IF_0_CONCAT_IF_s1_to_s2_fifo_first_BIT_28_THEN_ETC___d41 =
	     _0_CONCAT_IF_s1_to_s2_fifo_first_BIT_28_THEN_s1_ETC___d27[24] ?
	       ((_theResult_____1_fst__h854 == 8'd254) ?
		  31'h7F800000 :
		  { incrementedExp__h839,
		    _0_CONCAT_IF_s1_to_s2_fifo_first_BIT_28_THEN_s1_ETC___d27[23:1] }) :
	       { _theResult_____1_fst__h854, _theResult_____1_snd__h855 } ;
  assign IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d265 =
	     { x__h2032 ^ y__h2033,
	       IF_x723_BIT_0_XOR_x871_BIT_0_THEN_1_ELSE_0__q1[0] } ;
  assign IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d266 =
	     { x__h2228 ^ y__h2229,
	       x__h2130 ^ y__h2131,
	       IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d265 } ;
  assign IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d267 =
	     { x__h2424 ^ y__h2425,
	       x__h2326 ^ y__h2327,
	       IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d266 } ;
  assign IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d268 =
	     { x__h2620 ^ y__h2621,
	       x__h2522 ^ y__h2523,
	       IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d267 } ;
  assign IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d269 =
	     { x__h2816 ^ y__h2817,
	       x__h2718 ^ y__h2719,
	       IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d268 } ;
  assign IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d270 =
	     { x__h3012 ^ y__h3013,
	       x__h2914 ^ y__h2915,
	       IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d269 } ;
  assign IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d271 =
	     { x__h3208 ^ y__h3209,
	       x__h3110 ^ y__h3111,
	       IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d270 } ;
  assign IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d272 =
	     { x__h3404 ^ y__h3405,
	       x__h3306 ^ y__h3307,
	       IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d271 } ;
  assign IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d273 =
	     { x__h3600 ^ y__h3601,
	       x__h3502 ^ y__h3503,
	       IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d272 } ;
  assign IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d274 =
	     { x__h3796 ^ y__h3797,
	       x__h3698 ^ y__h3699,
	       IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d273 } ;
  assign IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d275 =
	     { x__h3992 ^ y__h3993,
	       x__h3894 ^ y__h3895,
	       IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d274 } ;
  assign IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d276 =
	     { x__h4188 ^ y__h4189,
	       x__h4090 ^ y__h4091,
	       IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d275 } ;
  assign IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d277 =
	     { x__h4384 ^ y__h4385,
	       x__h4286 ^ y__h4287,
	       IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d276 } ;
  assign IF_x723_BIT_0_XOR_x871_BIT_0_THEN_1_ELSE_0__q1 =
	     (x__h1723[0] ^ x__h1871[0]) ? 28'd1 : 28'd0 ;
  assign _0_CONCAT_IF_s1_to_s2_fifo_first_BIT_28_THEN_s1_ETC___d27 =
	     { 1'd0, sig24__h512 } +
	     (((s1_to_s2_fifo_D_OUT[28] ?
		  s1_to_s2_fifo_D_OUT[4] :
		  s1_to_s2_fifo_D_OUT[3]) &&
	       ((s1_to_s2_fifo_D_OUT[28] ?
		   s1_to_s2_fifo_D_OUT[3] ||
		   s1_to_s2_fifo_D_OUT[2] | s1_to_s2_fifo_D_OUT[1] :
		   s1_to_s2_fifo_D_OUT[2] || s1_to_s2_fifo_D_OUT[1]) ||
		sig24__h512[0])) ?
		25'd1 :
		25'd0) ;
  assign _0b1_CONCAT_put_a_BITS_22_TO_0_9_CONCAT_0b0_0_S_ETC___d52 =
	     mantA__h970 >> expDiff__h1019 ;
  assign _0b1_CONCAT_put_b_BITS_22_TO_0_4_CONCAT_0b0_5_S_ETC___d67 =
	     mantB__h971 >> expDiff__h1014 ;
  assign _theResult_____1_fst__h854 =
	     s1_to_s2_fifo_D_OUT[28] ?
	       newExp___1__h584 :
	       s1_to_s2_fifo_D_OUT[36:29] ;
  assign _theResult_____1_snd__h855 =
	     (_theResult_____1_fst__h854 == 8'hFF) ?
	       23'd0 :
	       _0_CONCAT_IF_s1_to_s2_fifo_first_BIT_28_THEN_s1_ETC___d27[22:0] ;
  assign _theResult___snd_snd__h1729 =
	     { _0b1_CONCAT_put_a_BITS_22_TO_0_9_CONCAT_0b0_0_S_ETC___d52[26:1],
	       _0b1_CONCAT_put_a_BITS_22_TO_0_9_CONCAT_0b0_0_S_ETC___d52[0] |
	       sticky__h1020 } ;
  assign _theResult___snd_snd__h1872 =
	     { _0b1_CONCAT_put_b_BITS_22_TO_0_4_CONCAT_0b0_5_S_ETC___d67[26:1],
	       _0b1_CONCAT_put_b_BITS_22_TO_0_4_CONCAT_0b0_5_S_ETC___d67[0] |
	       sticky__h1015 } ;
  assign expCommon__h974 =
	     put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO_23_6___d47 ?
	       put_b[30:23] :
	       put_a[30:23] ;
  assign expDiff__h1014 = put_a[30:23] - put_b[30:23] ;
  assign expDiff__h1019 = put_b[30:23] - put_a[30:23] ;
  assign incrementedExp__h839 = _theResult_____1_fst__h854 + 8'd1 ;
  assign mantA__h970 = { 1'b1, put_a[22:0], 3'b0 } ;
  assign mantB__h971 = { 1'b1, put_b[22:0], 3'b0 } ;
  assign mantSum__h976 =
	     { x__h4633 | y__h4634,
	       x__h4482 ^ y__h4483,
	       IF_put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO__ETC___d277 } ;
  assign newExp___1__h584 = s1_to_s2_fifo_D_OUT[36:29] + 8'd1 ;
  assign put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO_23_6___d47 =
	     put_a[30:23] <= put_b[30:23] ;
  assign sig24__h512 =
	     s1_to_s2_fifo_D_OUT[28] ?
	       s1_to_s2_fifo_D_OUT[28:5] :
	       s1_to_s2_fifo_D_OUT[27:4] ;
  assign sticky__h1015 = x__h1928 != 27'd0 ;
  assign sticky__h1020 = x__h1784 != 27'd0 ;
  assign x__h1723 =
	     put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO_23_6___d47 ?
	       _theResult___snd_snd__h1729 :
	       mantA__h970 ;
  assign x__h1784 = mantA__h970 & y__h1795 ;
  assign x__h1871 =
	     put_a_BITS_30_TO_23_5_ULE_put_b_BITS_30_TO_23_6___d47 ?
	       mantB__h971 :
	       _theResult___snd_snd__h1872 ;
  assign x__h1928 = mantB__h971 & y__h1939 ;
  assign x__h2032 = x__h1723[1] ^ x__h1871[1] ;
  assign x__h2130 = x__h1723[2] ^ x__h1871[2] ;
  assign x__h2183 = x__h1723[1] & x__h1871[1] ;
  assign x__h2228 = x__h1723[3] ^ x__h1871[3] ;
  assign x__h2281 = x__h1723[2] & x__h1871[2] ;
  assign x__h2326 = x__h1723[4] ^ x__h1871[4] ;
  assign x__h2379 = x__h1723[3] & x__h1871[3] ;
  assign x__h2424 = x__h1723[5] ^ x__h1871[5] ;
  assign x__h2477 = x__h1723[4] & x__h1871[4] ;
  assign x__h2522 = x__h1723[6] ^ x__h1871[6] ;
  assign x__h2575 = x__h1723[5] & x__h1871[5] ;
  assign x__h2620 = x__h1723[7] ^ x__h1871[7] ;
  assign x__h2673 = x__h1723[6] & x__h1871[6] ;
  assign x__h2718 = x__h1723[8] ^ x__h1871[8] ;
  assign x__h2771 = x__h1723[7] & x__h1871[7] ;
  assign x__h2816 = x__h1723[9] ^ x__h1871[9] ;
  assign x__h2869 = x__h1723[8] & x__h1871[8] ;
  assign x__h2914 = x__h1723[10] ^ x__h1871[10] ;
  assign x__h2967 = x__h1723[9] & x__h1871[9] ;
  assign x__h3012 = x__h1723[11] ^ x__h1871[11] ;
  assign x__h3065 = x__h1723[10] & x__h1871[10] ;
  assign x__h3110 = x__h1723[12] ^ x__h1871[12] ;
  assign x__h3163 = x__h1723[11] & x__h1871[11] ;
  assign x__h3208 = x__h1723[13] ^ x__h1871[13] ;
  assign x__h3261 = x__h1723[12] & x__h1871[12] ;
  assign x__h3306 = x__h1723[14] ^ x__h1871[14] ;
  assign x__h3359 = x__h1723[13] & x__h1871[13] ;
  assign x__h3404 = x__h1723[15] ^ x__h1871[15] ;
  assign x__h3457 = x__h1723[14] & x__h1871[14] ;
  assign x__h3502 = x__h1723[16] ^ x__h1871[16] ;
  assign x__h3555 = x__h1723[15] & x__h1871[15] ;
  assign x__h3600 = x__h1723[17] ^ x__h1871[17] ;
  assign x__h3653 = x__h1723[16] & x__h1871[16] ;
  assign x__h3698 = x__h1723[18] ^ x__h1871[18] ;
  assign x__h3751 = x__h1723[17] & x__h1871[17] ;
  assign x__h3796 = x__h1723[19] ^ x__h1871[19] ;
  assign x__h3849 = x__h1723[18] & x__h1871[18] ;
  assign x__h3894 = x__h1723[20] ^ x__h1871[20] ;
  assign x__h3947 = x__h1723[19] & x__h1871[19] ;
  assign x__h3992 = x__h1723[21] ^ x__h1871[21] ;
  assign x__h4045 = x__h1723[20] & x__h1871[20] ;
  assign x__h4090 = x__h1723[22] ^ x__h1871[22] ;
  assign x__h4143 = x__h1723[21] & x__h1871[21] ;
  assign x__h4188 = x__h1723[23] ^ x__h1871[23] ;
  assign x__h4241 = x__h1723[22] & x__h1871[22] ;
  assign x__h4286 = x__h1723[24] ^ x__h1871[24] ;
  assign x__h4339 = x__h1723[23] & x__h1871[23] ;
  assign x__h4384 = x__h1723[25] ^ x__h1871[25] ;
  assign x__h4437 = x__h1723[24] & x__h1871[24] ;
  assign x__h4482 = x__h1723[26] ^ x__h1871[26] ;
  assign x__h4535 = x__h1723[25] & x__h1871[25] ;
  assign x__h4633 = x__h1723[26] & x__h1871[26] ;
  assign y__h1795 = (27'd1 << expDiff__h1019) - 27'd1 ;
  assign y__h1939 = (27'd1 << expDiff__h1014) - 27'd1 ;
  assign y__h2033 = x__h1723[0] & x__h1871[0] ;
  assign y__h2131 = x__h2183 | y__h2184 ;
  assign y__h2184 = y__h2033 & x__h2032 ;
  assign y__h2229 = x__h2281 | y__h2282 ;
  assign y__h2282 = y__h2131 & x__h2130 ;
  assign y__h2327 = x__h2379 | y__h2380 ;
  assign y__h2380 = y__h2229 & x__h2228 ;
  assign y__h2425 = x__h2477 | y__h2478 ;
  assign y__h2478 = y__h2327 & x__h2326 ;
  assign y__h2523 = x__h2575 | y__h2576 ;
  assign y__h2576 = y__h2425 & x__h2424 ;
  assign y__h2621 = x__h2673 | y__h2674 ;
  assign y__h2674 = y__h2523 & x__h2522 ;
  assign y__h2719 = x__h2771 | y__h2772 ;
  assign y__h2772 = y__h2621 & x__h2620 ;
  assign y__h2817 = x__h2869 | y__h2870 ;
  assign y__h2870 = y__h2719 & x__h2718 ;
  assign y__h2915 = x__h2967 | y__h2968 ;
  assign y__h2968 = y__h2817 & x__h2816 ;
  assign y__h3013 = x__h3065 | y__h3066 ;
  assign y__h3066 = y__h2915 & x__h2914 ;
  assign y__h3111 = x__h3163 | y__h3164 ;
  assign y__h3164 = y__h3013 & x__h3012 ;
  assign y__h3209 = x__h3261 | y__h3262 ;
  assign y__h3262 = y__h3111 & x__h3110 ;
  assign y__h3307 = x__h3359 | y__h3360 ;
  assign y__h3360 = y__h3209 & x__h3208 ;
  assign y__h3405 = x__h3457 | y__h3458 ;
  assign y__h3458 = y__h3307 & x__h3306 ;
  assign y__h3503 = x__h3555 | y__h3556 ;
  assign y__h3556 = y__h3405 & x__h3404 ;
  assign y__h3601 = x__h3653 | y__h3654 ;
  assign y__h3654 = y__h3503 & x__h3502 ;
  assign y__h3699 = x__h3751 | y__h3752 ;
  assign y__h3752 = y__h3601 & x__h3600 ;
  assign y__h3797 = x__h3849 | y__h3850 ;
  assign y__h3850 = y__h3699 & x__h3698 ;
  assign y__h3895 = x__h3947 | y__h3948 ;
  assign y__h3948 = y__h3797 & x__h3796 ;
  assign y__h3993 = x__h4045 | y__h4046 ;
  assign y__h4046 = y__h3895 & x__h3894 ;
  assign y__h4091 = x__h4143 | y__h4144 ;
  assign y__h4144 = y__h3993 & x__h3992 ;
  assign y__h4189 = x__h4241 | y__h4242 ;
  assign y__h4242 = y__h4091 & x__h4090 ;
  assign y__h4287 = x__h4339 | y__h4340 ;
  assign y__h4340 = y__h4189 & x__h4188 ;
  assign y__h4385 = x__h4437 | y__h4438 ;
  assign y__h4438 = y__h4287 & x__h4286 ;
  assign y__h4483 = x__h4535 | y__h4536 ;
  assign y__h4536 = y__h4385 & x__h4384 ;
  assign y__h4634 = y__h4483 & x__h4482 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        result_fifo_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
      end
    else
      begin
        if (result_fifo_rv_EN)
	  result_fifo_rv <= `BSV_ASSIGNMENT_DELAY result_fifo_rv_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    result_fifo_rv = 33'h0AAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkFPadder32

